//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKjiemeitao.WPFUI.SSWCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSProductDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSProductDataObject")]
    [System.SerializableAttribute()]
    public class SSProductDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSProductDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSBrandSynonymsDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSBrandSynonymsDataObject")]
    [System.SerializableAttribute()]
    public class SSBrandSynonymsDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSBrandSynonymsDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSCategoryDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSCategoryDataObject")]
    [System.SerializableAttribute()]
    public class SSCategoryDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSCategoryDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSSizeDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSSizeDataObject")]
    [System.SerializableAttribute()]
    public class SSSizeDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSSizeDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSProductColorImageMappingtDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSProductColorImageMappingtDataObject")]
    [System.SerializableAttribute()]
    public class SSProductColorImageMappingtDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSProductColorImageMappingtDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSImageDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSImageDataObject")]
    [System.SerializableAttribute()]
    public class SSImageDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSImageDataObject> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UKjiemeitao.taobao.com", ConfigurationName="SSWCFService.IShopStyleService")]
    public interface IShopStyleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/GetProduct", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/GetProductResponse")]
        UKjiemeitao.WPFUI.SSWCFService.SSProductDataObjectList GetProduct(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/GetProduct", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/GetProductResponse")]
        System.Threading.Tasks.Task<UKjiemeitao.WPFUI.SSWCFService.SSProductDataObjectList> GetProductAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/TranslateProduct", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/TranslateProductResponse")]
        bool TranslateProduct(UKjiemeitao.Application.DataObjects.SSProductDataObject product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/TranslateProduct", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/TranslateProductResponse")]
        System.Threading.Tasks.Task<bool> TranslateProductAsync(UKjiemeitao.Application.DataObjects.SSProductDataObject product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/GetProductByID", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/GetProductByIDResponse")]
        UKjiemeitao.Application.DataObjects.SSProductDataObject GetProductByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/GetProductByID", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/GetProductByIDResponse")]
        System.Threading.Tasks.Task<UKjiemeitao.Application.DataObjects.SSProductDataObject> GetProductByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadRetailers", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadRetailersResponse")]
        void DownloadRetailers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadRetailers", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadRetailersResponse")]
        System.Threading.Tasks.Task DownloadRetailersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadBrands", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadBrandsResponse")]
        void DownloadBrands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadBrands", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadBrandsResponse")]
        System.Threading.Tasks.Task DownloadBrandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadColors", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadColorsResponse")]
        void DownloadColors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadColors", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadColorsResponse")]
        System.Threading.Tasks.Task DownloadColorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadSizes", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadSizesResponse")]
        void DownloadSizes(string catParentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadSizes", ReplyAction="http://UKjiemeitao.taobao.com/IShopStyleService/DownloadSizesResponse")]
        System.Threading.Tasks.Task DownloadSizesAsync(string catParentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopStyleServiceChannel : UKjiemeitao.WPFUI.SSWCFService.IShopStyleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopStyleServiceClient : System.ServiceModel.ClientBase<UKjiemeitao.WPFUI.SSWCFService.IShopStyleService>, UKjiemeitao.WPFUI.SSWCFService.IShopStyleService {
        
        public ShopStyleServiceClient() {
        }
        
        public ShopStyleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopStyleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopStyleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopStyleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UKjiemeitao.WPFUI.SSWCFService.SSProductDataObjectList GetProduct(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetProduct(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<UKjiemeitao.WPFUI.SSWCFService.SSProductDataObjectList> GetProductAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.GetProductAsync(startDate, endDate);
        }
        
        public bool TranslateProduct(UKjiemeitao.Application.DataObjects.SSProductDataObject product) {
            return base.Channel.TranslateProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> TranslateProductAsync(UKjiemeitao.Application.DataObjects.SSProductDataObject product) {
            return base.Channel.TranslateProductAsync(product);
        }
        
        public UKjiemeitao.Application.DataObjects.SSProductDataObject GetProductByID(string id) {
            return base.Channel.GetProductByID(id);
        }
        
        public System.Threading.Tasks.Task<UKjiemeitao.Application.DataObjects.SSProductDataObject> GetProductByIDAsync(string id) {
            return base.Channel.GetProductByIDAsync(id);
        }
        
        public void DownloadRetailers() {
            base.Channel.DownloadRetailers();
        }
        
        public System.Threading.Tasks.Task DownloadRetailersAsync() {
            return base.Channel.DownloadRetailersAsync();
        }
        
        public void DownloadBrands() {
            base.Channel.DownloadBrands();
        }
        
        public System.Threading.Tasks.Task DownloadBrandsAsync() {
            return base.Channel.DownloadBrandsAsync();
        }
        
        public void DownloadColors() {
            base.Channel.DownloadColors();
        }
        
        public System.Threading.Tasks.Task DownloadColorsAsync() {
            return base.Channel.DownloadColorsAsync();
        }
        
        public void DownloadSizes(string catParentID) {
            base.Channel.DownloadSizes(catParentID);
        }
        
        public System.Threading.Tasks.Task DownloadSizesAsync(string catParentID) {
            return base.Channel.DownloadSizesAsync(catParentID);
        }
    }
}
