//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKjiemeitao.WPFUI.TBWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://UKjiemeitao.taobao.com", ConfigurationName="TBWCFService.ITBProductUploadService")]
    public interface ITBProductUploadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemCat", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemCatRespon" +
            "se")]
        void InitializationItemCat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemCat", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemCatRespon" +
            "se")]
        System.Threading.Tasks.Task InitializationItemCatAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemProp", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemPropRespo" +
            "nse")]
        void InitializationItemProp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemProp", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationItemPropRespo" +
            "nse")]
        System.Threading.Tasks.Task InitializationItemPropAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationPropValue", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationPropValueResp" +
            "onse")]
        void InitializationPropValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationPropValue", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/InitializationPropValueResp" +
            "onse")]
        System.Threading.Tasks.Task InitializationPropValueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/ConvertSSProductToTaoBao", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/ConvertSSProductToTaoBaoRes" +
            "ponse")]
        void ConvertSSProductToTaoBao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/ConvertSSProductToTaoBao", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/ConvertSSProductToTaoBaoRes" +
            "ponse")]
        System.Threading.Tasks.Task ConvertSSProductToTaoBaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/UploadProduct", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/UploadProductResponse")]
        void UploadProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://UKjiemeitao.taobao.com/ITBProductUploadService/UploadProduct", ReplyAction="http://UKjiemeitao.taobao.com/ITBProductUploadService/UploadProductResponse")]
        System.Threading.Tasks.Task UploadProductAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITBProductUploadServiceChannel : UKjiemeitao.WPFUI.TBWCFService.ITBProductUploadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TBProductUploadServiceClient : System.ServiceModel.ClientBase<UKjiemeitao.WPFUI.TBWCFService.ITBProductUploadService>, UKjiemeitao.WPFUI.TBWCFService.ITBProductUploadService {
        
        public TBProductUploadServiceClient() {
        }
        
        public TBProductUploadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TBProductUploadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TBProductUploadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TBProductUploadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializationItemCat() {
            base.Channel.InitializationItemCat();
        }
        
        public System.Threading.Tasks.Task InitializationItemCatAsync() {
            return base.Channel.InitializationItemCatAsync();
        }
        
        public void InitializationItemProp() {
            base.Channel.InitializationItemProp();
        }
        
        public System.Threading.Tasks.Task InitializationItemPropAsync() {
            return base.Channel.InitializationItemPropAsync();
        }
        
        public void InitializationPropValue() {
            base.Channel.InitializationPropValue();
        }
        
        public System.Threading.Tasks.Task InitializationPropValueAsync() {
            return base.Channel.InitializationPropValueAsync();
        }
        
        public void ConvertSSProductToTaoBao() {
            base.Channel.ConvertSSProductToTaoBao();
        }
        
        public System.Threading.Tasks.Task ConvertSSProductToTaoBaoAsync() {
            return base.Channel.ConvertSSProductToTaoBaoAsync();
        }
        
        public void UploadProduct() {
            base.Channel.UploadProduct();
        }
        
        public System.Threading.Tasks.Task UploadProductAsync() {
            return base.Channel.UploadProductAsync();
        }
    }
}
