//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKjiemeitao.Application.DataObjects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBItemPropDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBItemPropDataObject")]
    public class TBItemPropDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBItemPropDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBItemPropDataObject", Namespace="http://UKjiemeitao.taobao.com/TBItemPropDataObject.xsd")]
    public partial class TBItemPropDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string ItemCatIDField;
        
        private System.Nullable<long> CidField;
        
        private System.Nullable<long> PidField;
        
        private System.Nullable<long> ParentPidField;
        
        private System.Nullable<long> ParentVidField;
        
        private string ChildTemplateField;
        
        private System.Nullable<bool> IsAllowAliasField;
        
        private System.Nullable<bool> IsColorPropField;
        
        private System.Nullable<bool> IsEnumPropField;
        
        private System.Nullable<bool> IsInputPropField;
        
        private System.Nullable<bool> IsItemPropField;
        
        private System.Nullable<bool> IsKeyPropField;
        
        private System.Nullable<bool> IsSalePropField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        private string ModifiedTypeField;
        
        private System.Nullable<bool> MultiField;
        
        private System.Nullable<bool> MustField;
        
        private string NameField;
        
        private System.Nullable<bool> RequiredField;
        
        private System.Nullable<int> SortOrderField;
        
        private string StatusField;
        
        private UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCatField;
        
        private UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCatID
        {
            get
            {
                return this.ItemCatIDField;
            }
            set
            {
                this.ItemCatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<long> Pid
        {
            get
            {
                return this.PidField;
            }
            set
            {
                this.PidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<long> ParentPid
        {
            get
            {
                return this.ParentPidField;
            }
            set
            {
                this.ParentPidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<long> ParentVid
        {
            get
            {
                return this.ParentVidField;
            }
            set
            {
                this.ParentVidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ChildTemplate
        {
            get
            {
                return this.ChildTemplateField;
            }
            set
            {
                this.ChildTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<bool> IsAllowAlias
        {
            get
            {
                return this.IsAllowAliasField;
            }
            set
            {
                this.IsAllowAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<bool> IsColorProp
        {
            get
            {
                return this.IsColorPropField;
            }
            set
            {
                this.IsColorPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<bool> IsEnumProp
        {
            get
            {
                return this.IsEnumPropField;
            }
            set
            {
                this.IsEnumPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<bool> IsInputProp
        {
            get
            {
                return this.IsInputPropField;
            }
            set
            {
                this.IsInputPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<bool> IsItemProp
        {
            get
            {
                return this.IsItemPropField;
            }
            set
            {
                this.IsItemPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> IsKeyProp
        {
            get
            {
                return this.IsKeyPropField;
            }
            set
            {
                this.IsKeyPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<bool> IsSaleProp
        {
            get
            {
                return this.IsSalePropField;
            }
            set
            {
                this.IsSalePropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<System.DateTime> ModifiedTime
        {
            get
            {
                return this.ModifiedTimeField;
            }
            set
            {
                this.ModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string ModifiedType
        {
            get
            {
                return this.ModifiedTypeField;
            }
            set
            {
                this.ModifiedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<bool> Multi
        {
            get
            {
                return this.MultiField;
            }
            set
            {
                this.MultiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<bool> Must
        {
            get
            {
                return this.MustField;
            }
            set
            {
                this.MustField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<bool> Required
        {
            get
            {
                return this.RequiredField;
            }
            set
            {
                this.RequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<int> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCat
        {
            get
            {
                return this.ItemCatField;
            }
            set
            {
                this.ItemCatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueList
        {
            get
            {
                return this.PropValueListField;
            }
            set
            {
                this.PropValueListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBItemCatDataObject", Namespace="http://UKjiemeitao.taobao.com/TBItemCatDataObject.xsd")]
    public partial class TBItemCatDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private System.Nullable<long> CidField;
        
        private string NameField;
        
        private System.Nullable<bool> IsParentField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        private string ModifiedTypeField;
        
        private System.Nullable<long> ParentCidField;
        
        private System.Nullable<int> SortOrderField;
        
        private string StatusField;
        
        private UKjiemeitao.Application.DataObjects.TBItemPropDataObjectList ItemPropListField;
        
        private UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this.IsParentField;
            }
            set
            {
                this.IsParentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> ModifiedTime
        {
            get
            {
                return this.ModifiedTimeField;
            }
            set
            {
                this.ModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ModifiedType
        {
            get
            {
                return this.ModifiedTypeField;
            }
            set
            {
                this.ModifiedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<long> ParentCid
        {
            get
            {
                return this.ParentCidField;
            }
            set
            {
                this.ParentCidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public UKjiemeitao.Application.DataObjects.TBItemPropDataObjectList ItemPropList
        {
            get
            {
                return this.ItemPropListField;
            }
            set
            {
                this.ItemPropListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueList
        {
            get
            {
                return this.PropValueListField;
            }
            set
            {
                this.PropValueListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBPropValueDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBPropValueDataObject")]
    public class TBPropValueDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBPropValueDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBPropValueDataObject", Namespace="http://UKjiemeitao.taobao.com/TBPropValueDataObject.xsd")]
    public partial class TBPropValueDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string ItemCatIDField;
        
        private string ItemPropIDField;
        
        private System.Nullable<long> CidField;
        
        private System.Nullable<bool> IsParentField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        private string ModifiedTypeField;
        
        private string NameField;
        
        private string NameAliasField;
        
        private System.Nullable<long> PidField;
        
        private string PropNameField;
        
        private System.Nullable<int> SortOrderField;
        
        private string StatusField;
        
        private System.Nullable<long> VidField;
        
        private UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCatField;
        
        private UKjiemeitao.Application.DataObjects.TBItemPropDataObject ItemPropField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCatID
        {
            get
            {
                return this.ItemCatIDField;
            }
            set
            {
                this.ItemCatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemPropID
        {
            get
            {
                return this.ItemPropIDField;
            }
            set
            {
                this.ItemPropIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this.IsParentField;
            }
            set
            {
                this.IsParentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> ModifiedTime
        {
            get
            {
                return this.ModifiedTimeField;
            }
            set
            {
                this.ModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ModifiedType
        {
            get
            {
                return this.ModifiedTypeField;
            }
            set
            {
                this.ModifiedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string NameAlias
        {
            get
            {
                return this.NameAliasField;
            }
            set
            {
                this.NameAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<long> Pid
        {
            get
            {
                return this.PidField;
            }
            set
            {
                this.PidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PropName
        {
            get
            {
                return this.PropNameField;
            }
            set
            {
                this.PropNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<int> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<long> Vid
        {
            get
            {
                return this.VidField;
            }
            set
            {
                this.VidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCat
        {
            get
            {
                return this.ItemCatField;
            }
            set
            {
                this.ItemCatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public UKjiemeitao.Application.DataObjects.TBItemPropDataObject ItemProp
        {
            get
            {
                return this.ItemPropField;
            }
            set
            {
                this.ItemPropField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBItemCatDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBItemCatDataObject")]
    public class TBItemCatDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBItemCatDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBProductDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBProductDataObject")]
    public class TBProductDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBProductDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBProductDataObject", Namespace="http://UKjiemeitao.taobao.com/TBProductDataObject.xsd")]
    public partial class TBProductDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private System.Nullable<long> ProductIdField;
        
        private string TitleField;
        
        private string DescField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<decimal> ShopPriceField;
        
        private System.Nullable<decimal> StandardPriceField;
        
        private string Stuff_StatusField;
        
        private System.Nullable<long> CidField;
        
        private string CatNameField;
        
        private string PropertyAliasField;
        
        private string PropsField;
        
        private string PropsStrField;
        
        private string SalePropsField;
        
        private string SalePropsStrField;
        
        private string BindsField;
        
        private string BindsStrField;
        
        private string CustomerPropsField;
        
        private System.Nullable<System.DateTime> CreatedField;
        
        private System.Nullable<System.DateTime> ModifiedField;
        
        private string PicPathField;
        
        private string PicUrlField;
        
        private string SellPtField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> ShopPrice
        {
            get
            {
                return this.ShopPriceField;
            }
            set
            {
                this.ShopPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> StandardPrice
        {
            get
            {
                return this.StandardPriceField;
            }
            set
            {
                this.StandardPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Stuff_Status
        {
            get
            {
                return this.Stuff_StatusField;
            }
            set
            {
                this.Stuff_StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CatName
        {
            get
            {
                return this.CatNameField;
            }
            set
            {
                this.CatNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PropertyAlias
        {
            get
            {
                return this.PropertyAliasField;
            }
            set
            {
                this.PropertyAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Props
        {
            get
            {
                return this.PropsField;
            }
            set
            {
                this.PropsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string PropsStr
        {
            get
            {
                return this.PropsStrField;
            }
            set
            {
                this.PropsStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string SaleProps
        {
            get
            {
                return this.SalePropsField;
            }
            set
            {
                this.SalePropsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string SalePropsStr
        {
            get
            {
                return this.SalePropsStrField;
            }
            set
            {
                this.SalePropsStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Binds
        {
            get
            {
                return this.BindsField;
            }
            set
            {
                this.BindsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string BindsStr
        {
            get
            {
                return this.BindsStrField;
            }
            set
            {
                this.BindsStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string CustomerProps
        {
            get
            {
                return this.CustomerPropsField;
            }
            set
            {
                this.CustomerPropsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<System.DateTime> Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<System.DateTime> Modified
        {
            get
            {
                return this.ModifiedField;
            }
            set
            {
                this.ModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string PicPath
        {
            get
            {
                return this.PicPathField;
            }
            set
            {
                this.PicPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string PicUrl
        {
            get
            {
                return this.PicUrlField;
            }
            set
            {
                this.PicUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string SellPt
        {
            get
            {
                return this.SellPtField;
            }
            set
            {
                this.SellPtField = value;
            }
        }
    }
}
