#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKJiemeitaoProductUploader.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Catalog")]
	public partial class TaoBaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_ItemCat(TB_ItemCat instance);
    partial void UpdateTB_ItemCat(TB_ItemCat instance);
    partial void DeleteTB_ItemCat(TB_ItemCat instance);
    partial void InsertTB_ItemProp(TB_ItemProp instance);
    partial void UpdateTB_ItemProp(TB_ItemProp instance);
    partial void DeleteTB_ItemProp(TB_ItemProp instance);
    partial void InsertTB_Product(TB_Product instance);
    partial void UpdateTB_Product(TB_Product instance);
    partial void DeleteTB_Product(TB_Product instance);
    partial void InsertTB_PropValue(TB_PropValue instance);
    partial void UpdateTB_PropValue(TB_PropValue instance);
    partial void DeleteTB_PropValue(TB_PropValue instance);
    #endregion
		
		public TaoBaoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CatalogConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_ItemCat> TB_ItemCats
		{
			get
			{
				return this.GetTable<TB_ItemCat>();
			}
		}
		
		public System.Data.Linq.Table<TB_ItemProp> TB_ItemProps
		{
			get
			{
				return this.GetTable<TB_ItemProp>();
			}
		}
		
		public System.Data.Linq.Table<TB_Product> TB_Products
		{
			get
			{
				return this.GetTable<TB_Product>();
			}
		}
		
		public System.Data.Linq.Table<TB_PropValue> TB_PropValues
		{
			get
			{
				return this.GetTable<TB_PropValue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ItemCat")]
	public partial class TB_ItemCat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<long> _Cid;
		
		private string _Name;
		
		private System.Nullable<bool> _IsParent;
		
		private System.Nullable<System.DateTime> _ModifiedTime;
		
		private string _ModifiedType;
		
		private System.Nullable<long> _ParentCid;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCidChanging(System.Nullable<long> value);
    partial void OnCidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIsParentChanging(System.Nullable<bool> value);
    partial void OnIsParentChanged();
    partial void OnModifiedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedTimeChanged();
    partial void OnModifiedTypeChanging(string value);
    partial void OnModifiedTypeChanged();
    partial void OnParentCidChanging(System.Nullable<long> value);
    partial void OnParentCidChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public TB_ItemCat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="BigInt")]
		public System.Nullable<long> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="Bit")]
		public System.Nullable<bool> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedTime
		{
			get
			{
				return this._ModifiedTime;
			}
			set
			{
				if ((this._ModifiedTime != value))
				{
					this.OnModifiedTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedTime = value;
					this.SendPropertyChanged("ModifiedTime");
					this.OnModifiedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedType", DbType="NChar(50)")]
		public string ModifiedType
		{
			get
			{
				return this._ModifiedType;
			}
			set
			{
				if ((this._ModifiedType != value))
				{
					this.OnModifiedTypeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedType = value;
					this.SendPropertyChanged("ModifiedType");
					this.OnModifiedTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCid", DbType="BigInt")]
		public System.Nullable<long> ParentCid
		{
			get
			{
				return this._ParentCid;
			}
			set
			{
				if ((this._ParentCid != value))
				{
					this.OnParentCidChanging(value);
					this.SendPropertyChanging();
					this._ParentCid = value;
					this.SendPropertyChanged("ParentCid");
					this.OnParentCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ItemProp")]
	public partial class TB_ItemProp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _Pid;
		
		private System.Nullable<int> _ParentPid;
		
		private System.Nullable<int> _ParentVid;
		
		private string _ChildTemplate;
		
		private System.Nullable<bool> _IsAllowAlias;
		
		private System.Nullable<bool> _IsColorProp;
		
		private System.Nullable<bool> _IsEnumProp;
		
		private System.Nullable<bool> _IsInputProp;
		
		private System.Nullable<bool> _IsItemProp;
		
		private System.Nullable<bool> _IsKeyProp;
		
		private System.Nullable<bool> _IsSaleProp;
		
		private System.Nullable<System.DateTime> _ModifiedTime;
		
		private string _ModifiedType;
		
		private System.Nullable<bool> _Multi;
		
		private System.Nullable<bool> _Must;
		
		private string _Name;
		
		private System.Nullable<bool> _Required;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Status;
		
		private System.Nullable<int> _Cid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPidChanging(System.Nullable<int> value);
    partial void OnPidChanged();
    partial void OnParentPidChanging(System.Nullable<int> value);
    partial void OnParentPidChanged();
    partial void OnParentVidChanging(System.Nullable<int> value);
    partial void OnParentVidChanged();
    partial void OnChildTemplateChanging(string value);
    partial void OnChildTemplateChanged();
    partial void OnIsAllowAliasChanging(System.Nullable<bool> value);
    partial void OnIsAllowAliasChanged();
    partial void OnIsColorPropChanging(System.Nullable<bool> value);
    partial void OnIsColorPropChanged();
    partial void OnIsEnumPropChanging(System.Nullable<bool> value);
    partial void OnIsEnumPropChanged();
    partial void OnIsInputPropChanging(System.Nullable<bool> value);
    partial void OnIsInputPropChanged();
    partial void OnIsItemPropChanging(System.Nullable<bool> value);
    partial void OnIsItemPropChanged();
    partial void OnIsKeyPropChanging(System.Nullable<bool> value);
    partial void OnIsKeyPropChanged();
    partial void OnIsSalePropChanging(System.Nullable<bool> value);
    partial void OnIsSalePropChanged();
    partial void OnModifiedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedTimeChanged();
    partial void OnModifiedTypeChanging(string value);
    partial void OnModifiedTypeChanged();
    partial void OnMultiChanging(System.Nullable<bool> value);
    partial void OnMultiChanged();
    partial void OnMustChanging(System.Nullable<bool> value);
    partial void OnMustChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRequiredChanging(System.Nullable<bool> value);
    partial void OnRequiredChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCidChanging(System.Nullable<int> value);
    partial void OnCidChanged();
    #endregion
		
		public TB_ItemProp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int")]
		public System.Nullable<int> Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentPid", DbType="Int")]
		public System.Nullable<int> ParentPid
		{
			get
			{
				return this._ParentPid;
			}
			set
			{
				if ((this._ParentPid != value))
				{
					this.OnParentPidChanging(value);
					this.SendPropertyChanging();
					this._ParentPid = value;
					this.SendPropertyChanged("ParentPid");
					this.OnParentPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentVid", DbType="Int")]
		public System.Nullable<int> ParentVid
		{
			get
			{
				return this._ParentVid;
			}
			set
			{
				if ((this._ParentVid != value))
				{
					this.OnParentVidChanging(value);
					this.SendPropertyChanging();
					this._ParentVid = value;
					this.SendPropertyChanged("ParentVid");
					this.OnParentVidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildTemplate", DbType="NVarChar(2000)")]
		public string ChildTemplate
		{
			get
			{
				return this._ChildTemplate;
			}
			set
			{
				if ((this._ChildTemplate != value))
				{
					this.OnChildTemplateChanging(value);
					this.SendPropertyChanging();
					this._ChildTemplate = value;
					this.SendPropertyChanged("ChildTemplate");
					this.OnChildTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAllowAlias", DbType="Bit")]
		public System.Nullable<bool> IsAllowAlias
		{
			get
			{
				return this._IsAllowAlias;
			}
			set
			{
				if ((this._IsAllowAlias != value))
				{
					this.OnIsAllowAliasChanging(value);
					this.SendPropertyChanging();
					this._IsAllowAlias = value;
					this.SendPropertyChanged("IsAllowAlias");
					this.OnIsAllowAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsColorProp", DbType="Bit")]
		public System.Nullable<bool> IsColorProp
		{
			get
			{
				return this._IsColorProp;
			}
			set
			{
				if ((this._IsColorProp != value))
				{
					this.OnIsColorPropChanging(value);
					this.SendPropertyChanging();
					this._IsColorProp = value;
					this.SendPropertyChanged("IsColorProp");
					this.OnIsColorPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnumProp", DbType="Bit")]
		public System.Nullable<bool> IsEnumProp
		{
			get
			{
				return this._IsEnumProp;
			}
			set
			{
				if ((this._IsEnumProp != value))
				{
					this.OnIsEnumPropChanging(value);
					this.SendPropertyChanging();
					this._IsEnumProp = value;
					this.SendPropertyChanged("IsEnumProp");
					this.OnIsEnumPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInputProp", DbType="Bit")]
		public System.Nullable<bool> IsInputProp
		{
			get
			{
				return this._IsInputProp;
			}
			set
			{
				if ((this._IsInputProp != value))
				{
					this.OnIsInputPropChanging(value);
					this.SendPropertyChanging();
					this._IsInputProp = value;
					this.SendPropertyChanged("IsInputProp");
					this.OnIsInputPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsItemProp", DbType="Bit")]
		public System.Nullable<bool> IsItemProp
		{
			get
			{
				return this._IsItemProp;
			}
			set
			{
				if ((this._IsItemProp != value))
				{
					this.OnIsItemPropChanging(value);
					this.SendPropertyChanging();
					this._IsItemProp = value;
					this.SendPropertyChanged("IsItemProp");
					this.OnIsItemPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsKeyProp", DbType="Bit")]
		public System.Nullable<bool> IsKeyProp
		{
			get
			{
				return this._IsKeyProp;
			}
			set
			{
				if ((this._IsKeyProp != value))
				{
					this.OnIsKeyPropChanging(value);
					this.SendPropertyChanging();
					this._IsKeyProp = value;
					this.SendPropertyChanged("IsKeyProp");
					this.OnIsKeyPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSaleProp", DbType="Bit")]
		public System.Nullable<bool> IsSaleProp
		{
			get
			{
				return this._IsSaleProp;
			}
			set
			{
				if ((this._IsSaleProp != value))
				{
					this.OnIsSalePropChanging(value);
					this.SendPropertyChanging();
					this._IsSaleProp = value;
					this.SendPropertyChanged("IsSaleProp");
					this.OnIsSalePropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedTime
		{
			get
			{
				return this._ModifiedTime;
			}
			set
			{
				if ((this._ModifiedTime != value))
				{
					this.OnModifiedTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedTime = value;
					this.SendPropertyChanged("ModifiedTime");
					this.OnModifiedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedType", DbType="NChar(50)")]
		public string ModifiedType
		{
			get
			{
				return this._ModifiedType;
			}
			set
			{
				if ((this._ModifiedType != value))
				{
					this.OnModifiedTypeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedType = value;
					this.SendPropertyChanged("ModifiedType");
					this.OnModifiedTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Multi", DbType="Bit")]
		public System.Nullable<bool> Multi
		{
			get
			{
				return this._Multi;
			}
			set
			{
				if ((this._Multi != value))
				{
					this.OnMultiChanging(value);
					this.SendPropertyChanging();
					this._Multi = value;
					this.SendPropertyChanged("Multi");
					this.OnMultiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Must", DbType="Bit")]
		public System.Nullable<bool> Must
		{
			get
			{
				return this._Must;
			}
			set
			{
				if ((this._Must != value))
				{
					this.OnMustChanging(value);
					this.SendPropertyChanging();
					this._Must = value;
					this.SendPropertyChanged("Must");
					this.OnMustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Required", DbType="Bit")]
		public System.Nullable<bool> Required
		{
			get
			{
				return this._Required;
			}
			set
			{
				if ((this._Required != value))
				{
					this.OnRequiredChanging(value);
					this.SendPropertyChanging();
					this._Required = value;
					this.SendPropertyChanged("Required");
					this.OnRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="Int")]
		public System.Nullable<int> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Product")]
	public partial class TB_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<int> _ProductId;
		
		private string _Title;
		
		private string _Desc;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<decimal> _ShopPrice;
		
		private System.Nullable<decimal> _StandardPrice;
		
		private string _Stuff_Status;
		
		private System.Nullable<int> _Cid;
		
		private string _CatName;
		
		private string _PropertyAlias;
		
		private string _Props;
		
		private string _PropsStr;
		
		private string _SaleProps;
		
		private string _SalePropsStr;
		
		private string _Binds;
		
		private string _BindsStr;
		
		private string _CustomerProps;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<System.DateTime> _Modified;
		
		private string _PicPath;
		
		private string _PicUrl;
		
		private string _SellPt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnProductIdChanging(System.Nullable<int> value);
    partial void OnProductIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnShopPriceChanging(System.Nullable<decimal> value);
    partial void OnShopPriceChanged();
    partial void OnStandardPriceChanging(System.Nullable<decimal> value);
    partial void OnStandardPriceChanged();
    partial void OnStuff_StatusChanging(string value);
    partial void OnStuff_StatusChanged();
    partial void OnCidChanging(System.Nullable<int> value);
    partial void OnCidChanged();
    partial void OnCatNameChanging(string value);
    partial void OnCatNameChanged();
    partial void OnPropertyAliasChanging(string value);
    partial void OnPropertyAliasChanged();
    partial void OnPropsChanging(string value);
    partial void OnPropsChanged();
    partial void OnPropsStrChanging(string value);
    partial void OnPropsStrChanged();
    partial void OnSalePropsChanging(string value);
    partial void OnSalePropsChanged();
    partial void OnSalePropsStrChanging(string value);
    partial void OnSalePropsStrChanged();
    partial void OnBindsChanging(string value);
    partial void OnBindsChanged();
    partial void OnBindsStrChanging(string value);
    partial void OnBindsStrChanged();
    partial void OnCustomerPropsChanging(string value);
    partial void OnCustomerPropsChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedChanged();
    partial void OnPicPathChanging(string value);
    partial void OnPicPathChanged();
    partial void OnPicUrlChanging(string value);
    partial void OnPicUrlChanged();
    partial void OnSellPtChanging(string value);
    partial void OnSellPtChanged();
    #endregion
		
		public TB_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this.OnProductIdChanging(value);
					this.SendPropertyChanging();
					this._ProductId = value;
					this.SendPropertyChanged("ProductId");
					this.OnProductIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(30)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="NVarChar(4000)")]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this.OnDescChanging(value);
					this.SendPropertyChanging();
					this._Desc = value;
					this.SendPropertyChanged("Desc");
					this.OnDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShopPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> ShopPrice
		{
			get
			{
				return this._ShopPrice;
			}
			set
			{
				if ((this._ShopPrice != value))
				{
					this.OnShopPriceChanging(value);
					this.SendPropertyChanging();
					this._ShopPrice = value;
					this.SendPropertyChanged("ShopPrice");
					this.OnShopPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StandardPrice", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> StandardPrice
		{
			get
			{
				return this._StandardPrice;
			}
			set
			{
				if ((this._StandardPrice != value))
				{
					this.OnStandardPriceChanging(value);
					this.SendPropertyChanging();
					this._StandardPrice = value;
					this.SendPropertyChanged("StandardPrice");
					this.OnStandardPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stuff_Status", DbType="VarChar(50)")]
		public string Stuff_Status
		{
			get
			{
				return this._Stuff_Status;
			}
			set
			{
				if ((this._Stuff_Status != value))
				{
					this.OnStuff_StatusChanging(value);
					this.SendPropertyChanging();
					this._Stuff_Status = value;
					this.SendPropertyChanged("Stuff_Status");
					this.OnStuff_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="Int")]
		public System.Nullable<int> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(200)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this.OnCatNameChanging(value);
					this.SendPropertyChanging();
					this._CatName = value;
					this.SendPropertyChanged("CatName");
					this.OnCatNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyAlias", DbType="NVarChar(2000)")]
		public string PropertyAlias
		{
			get
			{
				return this._PropertyAlias;
			}
			set
			{
				if ((this._PropertyAlias != value))
				{
					this.OnPropertyAliasChanging(value);
					this.SendPropertyChanging();
					this._PropertyAlias = value;
					this.SendPropertyChanged("PropertyAlias");
					this.OnPropertyAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Props", DbType="NVarChar(2000)")]
		public string Props
		{
			get
			{
				return this._Props;
			}
			set
			{
				if ((this._Props != value))
				{
					this.OnPropsChanging(value);
					this.SendPropertyChanging();
					this._Props = value;
					this.SendPropertyChanged("Props");
					this.OnPropsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropsStr", DbType="NVarChar(4000)")]
		public string PropsStr
		{
			get
			{
				return this._PropsStr;
			}
			set
			{
				if ((this._PropsStr != value))
				{
					this.OnPropsStrChanging(value);
					this.SendPropertyChanging();
					this._PropsStr = value;
					this.SendPropertyChanged("PropsStr");
					this.OnPropsStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleProps", DbType="NVarChar(2000)")]
		public string SaleProps
		{
			get
			{
				return this._SaleProps;
			}
			set
			{
				if ((this._SaleProps != value))
				{
					this.OnSalePropsChanging(value);
					this.SendPropertyChanging();
					this._SaleProps = value;
					this.SendPropertyChanged("SaleProps");
					this.OnSalePropsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalePropsStr", DbType="NVarChar(4000)")]
		public string SalePropsStr
		{
			get
			{
				return this._SalePropsStr;
			}
			set
			{
				if ((this._SalePropsStr != value))
				{
					this.OnSalePropsStrChanging(value);
					this.SendPropertyChanging();
					this._SalePropsStr = value;
					this.SendPropertyChanged("SalePropsStr");
					this.OnSalePropsStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Binds", DbType="NVarChar(2000)")]
		public string Binds
		{
			get
			{
				return this._Binds;
			}
			set
			{
				if ((this._Binds != value))
				{
					this.OnBindsChanging(value);
					this.SendPropertyChanging();
					this._Binds = value;
					this.SendPropertyChanged("Binds");
					this.OnBindsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BindsStr", DbType="NVarChar(4000)")]
		public string BindsStr
		{
			get
			{
				return this._BindsStr;
			}
			set
			{
				if ((this._BindsStr != value))
				{
					this.OnBindsStrChanging(value);
					this.SendPropertyChanging();
					this._BindsStr = value;
					this.SendPropertyChanged("BindsStr");
					this.OnBindsStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerProps", DbType="NVarChar(2000)")]
		public string CustomerProps
		{
			get
			{
				return this._CustomerProps;
			}
			set
			{
				if ((this._CustomerProps != value))
				{
					this.OnCustomerPropsChanging(value);
					this.SendPropertyChanging();
					this._CustomerProps = value;
					this.SendPropertyChanged("CustomerProps");
					this.OnCustomerPropsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="DateTime")]
		public System.Nullable<System.DateTime> Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this.OnModifiedChanging(value);
					this.SendPropertyChanging();
					this._Modified = value;
					this.SendPropertyChanged("Modified");
					this.OnModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicPath", DbType="NChar(1000)")]
		public string PicPath
		{
			get
			{
				return this._PicPath;
			}
			set
			{
				if ((this._PicPath != value))
				{
					this.OnPicPathChanging(value);
					this.SendPropertyChanging();
					this._PicPath = value;
					this.SendPropertyChanged("PicPath");
					this.OnPicPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicUrl", DbType="NChar(1000)")]
		public string PicUrl
		{
			get
			{
				return this._PicUrl;
			}
			set
			{
				if ((this._PicUrl != value))
				{
					this.OnPicUrlChanging(value);
					this.SendPropertyChanging();
					this._PicUrl = value;
					this.SendPropertyChanged("PicUrl");
					this.OnPicUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellPt", DbType="NVarChar(20)")]
		public string SellPt
		{
			get
			{
				return this._SellPt;
			}
			set
			{
				if ((this._SellPt != value))
				{
					this.OnSellPtChanging(value);
					this.SendPropertyChanging();
					this._SellPt = value;
					this.SendPropertyChanged("SellPt");
					this.OnSellPtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PropValue")]
	public partial class TB_PropValue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<bool> _IsParent;
		
		private System.Nullable<System.DateTime> _ModifiedTime;
		
		private string _ModifiedType;
		
		private string _Name;
		
		private string _NameAlias;
		
		private System.Nullable<int> _Pid;
		
		private string _PropName;
		
		private System.Nullable<int> _SortOrder;
		
		private string _Status;
		
		private System.Nullable<int> _Vid;
		
		private System.Nullable<int> _Cid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIsParentChanging(System.Nullable<bool> value);
    partial void OnIsParentChanged();
    partial void OnModifiedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedTimeChanged();
    partial void OnModifiedTypeChanging(string value);
    partial void OnModifiedTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNameAliasChanging(string value);
    partial void OnNameAliasChanged();
    partial void OnPidChanging(System.Nullable<int> value);
    partial void OnPidChanged();
    partial void OnPropNameChanging(string value);
    partial void OnPropNameChanged();
    partial void OnSortOrderChanging(System.Nullable<int> value);
    partial void OnSortOrderChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnVidChanging(System.Nullable<int> value);
    partial void OnVidChanged();
    partial void OnCidChanging(System.Nullable<int> value);
    partial void OnCidChanged();
    #endregion
		
		public TB_PropValue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="Bit")]
		public System.Nullable<bool> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedTime
		{
			get
			{
				return this._ModifiedTime;
			}
			set
			{
				if ((this._ModifiedTime != value))
				{
					this.OnModifiedTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedTime = value;
					this.SendPropertyChanged("ModifiedTime");
					this.OnModifiedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedType", DbType="NChar(50)")]
		public string ModifiedType
		{
			get
			{
				return this._ModifiedType;
			}
			set
			{
				if ((this._ModifiedType != value))
				{
					this.OnModifiedTypeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedType = value;
					this.SendPropertyChanged("ModifiedType");
					this.OnModifiedTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameAlias", DbType="NVarChar(200)")]
		public string NameAlias
		{
			get
			{
				return this._NameAlias;
			}
			set
			{
				if ((this._NameAlias != value))
				{
					this.OnNameAliasChanging(value);
					this.SendPropertyChanging();
					this._NameAlias = value;
					this.SendPropertyChanged("NameAlias");
					this.OnNameAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="Int")]
		public System.Nullable<int> Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropName", DbType="NVarChar(200)")]
		public string PropName
		{
			get
			{
				return this._PropName;
			}
			set
			{
				if ((this._PropName != value))
				{
					this.OnPropNameChanging(value);
					this.SendPropertyChanging();
					this._PropName = value;
					this.SendPropertyChanged("PropName");
					this.OnPropNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int")]
		public System.Nullable<int> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vid", DbType="Int")]
		public System.Nullable<int> Vid
		{
			get
			{
				return this._Vid;
			}
			set
			{
				if ((this._Vid != value))
				{
					this.OnVidChanging(value);
					this.SendPropertyChanging();
					this._Vid = value;
					this.SendPropertyChanged("Vid");
					this.OnVidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="Int")]
		public System.Nullable<int> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
