//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKjiemeitao.Application.DataObjects
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSBrandDataObject", Namespace="http://UKjiemeitao.taobao.com/SSBrandDataObject.xsd")]
    public partial class SSBrandDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private long brand_idField;
        
        private string brand_nameField;
        
        private string urlField;
        
        private UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollectionField;
        
        private UKjiemeitao.Application.DataObjects.SSBrandSynonymsDataObjectList BrandSynonymsCollectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long brand_id
        {
            get
            {
                return this.brand_idField;
            }
            set
            {
                this.brand_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand_name
        {
            get
            {
                return this.brand_nameField;
            }
            set
            {
                this.brand_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollection
        {
            get
            {
                return this.ProductCollectionField;
            }
            set
            {
                this.ProductCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public UKjiemeitao.Application.DataObjects.SSBrandSynonymsDataObjectList BrandSynonymsCollection
        {
            get
            {
                return this.BrandSynonymsCollectionField;
            }
            set
            {
                this.BrandSynonymsCollectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSProductDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSProductDataObject")]
    public class SSProductDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSProductDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSBrandSynonymsDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSBrandSynonymsDataObject")]
    public class SSBrandSynonymsDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSBrandSynonymsDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSProductDataObject", Namespace="http://UKjiemeitao.taobao.com/SSProductDataObject.xsd")]
    public partial class SSProductDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private long product_idField;
        
        private string nameField;
        
        private string currencyField;
        
        private System.Nullable<decimal> priceField;
        
        private string price_labelField;
        
        private System.Nullable<decimal> sale_priceField;
        
        private string sale_price_labelField;
        
        private System.Nullable<bool> in_stockField;
        
        private System.Nullable<long> retailer_idField;
        
        private string localeField;
        
        private string descriptionField;
        
        private System.Nullable<long> brand_idField;
        
        private string click_urlField;
        
        private string page_urlField;
        
        private string image_idField;
        
        private string chinese_nameField;
        
        private string chinese_descriptionField;
        
        private System.Nullable<bool> IsTranslateField;
        
        private System.Nullable<System.DateTime> CreateDateField;
        
        private UKjiemeitao.Application.DataObjects.SSBrandDataObject BrandField;
        
        private UKjiemeitao.Application.DataObjects.SSRetailerDataObject RetailerField;
        
        private UKjiemeitao.Application.DataObjects.SSCategoryDataObjectList CategoryCollectionField;
        
        private UKjiemeitao.Application.DataObjects.SSSizeDataObjectList SizeCollectionField;
        
        private UKjiemeitao.Application.DataObjects.SSProductColorImageMappingtDataObjectList ColorCollectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long product_id
        {
            get
            {
                return this.product_idField;
            }
            set
            {
                this.product_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string price_label
        {
            get
            {
                return this.price_labelField;
            }
            set
            {
                this.price_labelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> sale_price
        {
            get
            {
                return this.sale_priceField;
            }
            set
            {
                this.sale_priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string sale_price_label
        {
            get
            {
                return this.sale_price_labelField;
            }
            set
            {
                this.sale_price_labelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<bool> in_stock
        {
            get
            {
                return this.in_stockField;
            }
            set
            {
                this.in_stockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<long> retailer_id
        {
            get
            {
                return this.retailer_idField;
            }
            set
            {
                this.retailer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<long> brand_id
        {
            get
            {
                return this.brand_idField;
            }
            set
            {
                this.brand_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string click_url
        {
            get
            {
                return this.click_urlField;
            }
            set
            {
                this.click_urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string page_url
        {
            get
            {
                return this.page_urlField;
            }
            set
            {
                this.page_urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string image_id
        {
            get
            {
                return this.image_idField;
            }
            set
            {
                this.image_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string chinese_name
        {
            get
            {
                return this.chinese_nameField;
            }
            set
            {
                this.chinese_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string chinese_description
        {
            get
            {
                return this.chinese_descriptionField;
            }
            set
            {
                this.chinese_descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<bool> IsTranslate
        {
            get
            {
                return this.IsTranslateField;
            }
            set
            {
                this.IsTranslateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public UKjiemeitao.Application.DataObjects.SSBrandDataObject Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public UKjiemeitao.Application.DataObjects.SSRetailerDataObject Retailer
        {
            get
            {
                return this.RetailerField;
            }
            set
            {
                this.RetailerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public UKjiemeitao.Application.DataObjects.SSCategoryDataObjectList CategoryCollection
        {
            get
            {
                return this.CategoryCollectionField;
            }
            set
            {
                this.CategoryCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public UKjiemeitao.Application.DataObjects.SSSizeDataObjectList SizeCollection
        {
            get
            {
                return this.SizeCollectionField;
            }
            set
            {
                this.SizeCollectionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public UKjiemeitao.Application.DataObjects.SSProductColorImageMappingtDataObjectList ColorCollection
        {
            get
            {
                return this.ColorCollectionField;
            }
            set
            {
                this.ColorCollectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSRetailerDataObject", Namespace="http://UKjiemeitao.taobao.com/SSRetailerDataObject.xsd")]
    public partial class SSRetailerDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private long retailer_idField;
        
        private string nameField;
        
        private string urlField;
        
        private System.Nullable<bool> deeplinkSupportField;
        
        private UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long retailer_id
        {
            get
            {
                return this.retailer_idField;
            }
            set
            {
                this.retailer_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> deeplinkSupport
        {
            get
            {
                return this.deeplinkSupportField;
            }
            set
            {
                this.deeplinkSupportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollection
        {
            get
            {
                return this.ProductCollectionField;
            }
            set
            {
                this.ProductCollectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSCategoryDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSCategoryDataObject")]
    public class SSCategoryDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSCategoryDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSSizeDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSSizeDataObject")]
    public class SSSizeDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSSizeDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSProductColorImageMappingtDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSProductColorImageMappingtDataObject")]
    public class SSProductColorImageMappingtDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSProductColorImageMappingtDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSCategoryDataObject", Namespace="http://UKjiemeitao.taobao.com/SSCategoryDataObject.xsd")]
    public partial class SSCategoryDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string cat_idField;
        
        private string localizedidField;
        
        private string shortnameField;
        
        private string nameField;
        
        private string parentidField;
        
        private UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string cat_id
        {
            get
            {
                return this.cat_idField;
            }
            set
            {
                this.cat_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string localizedid
        {
            get
            {
                return this.localizedidField;
            }
            set
            {
                this.localizedidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shortname
        {
            get
            {
                return this.shortnameField;
            }
            set
            {
                this.shortnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string parentid
        {
            get
            {
                return this.parentidField;
            }
            set
            {
                this.parentidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollection
        {
            get
            {
                return this.ProductCollectionField;
            }
            set
            {
                this.ProductCollectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSSizeDataObject", Namespace="http://UKjiemeitao.taobao.com/SSSizeDataObject.xsd")]
    public partial class SSSizeDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string size_idField;
        
        private string nameField;
        
        private string cat_idField;
        
        private UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string size_id
        {
            get
            {
                return this.size_idField;
            }
            set
            {
                this.size_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string cat_id
        {
            get
            {
                return this.cat_idField;
            }
            set
            {
                this.cat_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public UKjiemeitao.Application.DataObjects.SSProductDataObjectList ProductCollection
        {
            get
            {
                return this.ProductCollectionField;
            }
            set
            {
                this.ProductCollectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSProductColorImageMappingtDataObject", Namespace="http://UKjiemeitao.taobao.com/SSProductColorImageMappingtDataObject.xsd")]
    public partial class SSProductColorImageMappingtDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private long product_idField;
        
        private string color_nameField;
        
        private string image_idField;
        
        private UKjiemeitao.Application.DataObjects.SSProductDataObject ProductField;
        
        private UKjiemeitao.Application.DataObjects.SSImageDataObjectList ImageCollectionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long product_id
        {
            get
            {
                return this.product_idField;
            }
            set
            {
                this.product_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string color_name
        {
            get
            {
                return this.color_nameField;
            }
            set
            {
                this.color_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string image_id
        {
            get
            {
                return this.image_idField;
            }
            set
            {
                this.image_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public UKjiemeitao.Application.DataObjects.SSProductDataObject Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public UKjiemeitao.Application.DataObjects.SSImageDataObjectList ImageCollection
        {
            get
            {
                return this.ImageCollectionField;
            }
            set
            {
                this.ImageCollectionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSImageDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSImageDataObject")]
    public class SSImageDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSImageDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSImageDataObject", Namespace="http://UKjiemeitao.taobao.com/SSImageDataObject.xsd")]
    public partial class SSImageDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string image_idField;
        
        private string size_nameField;
        
        private System.Nullable<int> widthField;
        
        private System.Nullable<int> heightField;
        
        private string urlField;
        
        private UKjiemeitao.Application.DataObjects.SSProductColorImageMappingtDataObject ColorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_id
        {
            get
            {
                return this.image_idField;
            }
            set
            {
                this.image_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string size_name
        {
            get
            {
                return this.size_nameField;
            }
            set
            {
                this.size_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public UKjiemeitao.Application.DataObjects.SSProductColorImageMappingtDataObject Color
        {
            get
            {
                return this.ColorField;
            }
            set
            {
                this.ColorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSBrandSynonymsDataObject", Namespace="http://UKjiemeitao.taobao.com/SSBrandSynonymsDataObject.xsd")]
    public partial class SSBrandSynonymsDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private long brand_idField;
        
        private string synonyms_nameField;
        
        private UKjiemeitao.Application.DataObjects.SSBrandDataObject BrandField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long brand_id
        {
            get
            {
                return this.brand_idField;
            }
            set
            {
                this.brand_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string synonyms_name
        {
            get
            {
                return this.synonyms_nameField;
            }
            set
            {
                this.synonyms_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public UKjiemeitao.Application.DataObjects.SSBrandDataObject Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSBrandDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSBrandDataObject")]
    public class SSBrandDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSBrandDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSRetailerDataObjectList", Namespace="http://UKjiemeitao.taobao.com/SSCollectionDataObjectList.xsd", ItemName="SSRetailerDataObject")]
    public class SSRetailerDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSRetailerDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SSTBBrandMappingDataObject", Namespace="http://UKjiemeitao.taobao.com/SSTBBrandMappingDataObject.xsd")]
    public partial class SSTBBrandMappingDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private long brand_idField;
        
        private string brand_nameField;
        
        private string urlField;
        
        private System.Nullable<int> CidField;
        
        private string NameField;
        
        private string NameAliasField;
        
        private System.Nullable<int> PidField;
        
        private System.Nullable<int> VidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long brand_id
        {
            get
            {
                return this.brand_idField;
            }
            set
            {
                this.brand_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand_name
        {
            get
            {
                return this.brand_nameField;
            }
            set
            {
                this.brand_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string NameAlias
        {
            get
            {
                return this.NameAliasField;
            }
            set
            {
                this.NameAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> Pid
        {
            get
            {
                return this.PidField;
            }
            set
            {
                this.PidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<int> Vid
        {
            get
            {
                return this.VidField;
            }
            set
            {
                this.VidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBItemPropDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBItemPropDataObject")]
    public class TBItemPropDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBItemPropDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBItemPropDataObject", Namespace="http://UKjiemeitao.taobao.com/TBItemPropDataObject.xsd")]
    public partial class TBItemPropDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string ItemCatIDField;
        
        private System.Nullable<long> CidField;
        
        private System.Nullable<long> PidField;
        
        private System.Nullable<long> ParentPidField;
        
        private System.Nullable<long> ParentVidField;
        
        private string ChildTemplateField;
        
        private System.Nullable<bool> IsAllowAliasField;
        
        private System.Nullable<bool> IsColorPropField;
        
        private System.Nullable<bool> IsEnumPropField;
        
        private System.Nullable<bool> IsInputPropField;
        
        private System.Nullable<bool> IsItemPropField;
        
        private System.Nullable<bool> IsKeyPropField;
        
        private System.Nullable<bool> IsSalePropField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        private string ModifiedTypeField;
        
        private System.Nullable<bool> MultiField;
        
        private System.Nullable<bool> MustField;
        
        private string NameField;
        
        private System.Nullable<bool> RequiredField;
        
        private System.Nullable<int> SortOrderField;
        
        private string StatusField;
        
        private UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCatField;
        
        private UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCatID
        {
            get
            {
                return this.ItemCatIDField;
            }
            set
            {
                this.ItemCatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<long> Pid
        {
            get
            {
                return this.PidField;
            }
            set
            {
                this.PidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<long> ParentPid
        {
            get
            {
                return this.ParentPidField;
            }
            set
            {
                this.ParentPidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<long> ParentVid
        {
            get
            {
                return this.ParentVidField;
            }
            set
            {
                this.ParentVidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ChildTemplate
        {
            get
            {
                return this.ChildTemplateField;
            }
            set
            {
                this.ChildTemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<bool> IsAllowAlias
        {
            get
            {
                return this.IsAllowAliasField;
            }
            set
            {
                this.IsAllowAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<bool> IsColorProp
        {
            get
            {
                return this.IsColorPropField;
            }
            set
            {
                this.IsColorPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<bool> IsEnumProp
        {
            get
            {
                return this.IsEnumPropField;
            }
            set
            {
                this.IsEnumPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<bool> IsInputProp
        {
            get
            {
                return this.IsInputPropField;
            }
            set
            {
                this.IsInputPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<bool> IsItemProp
        {
            get
            {
                return this.IsItemPropField;
            }
            set
            {
                this.IsItemPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<bool> IsKeyProp
        {
            get
            {
                return this.IsKeyPropField;
            }
            set
            {
                this.IsKeyPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<bool> IsSaleProp
        {
            get
            {
                return this.IsSalePropField;
            }
            set
            {
                this.IsSalePropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.Nullable<System.DateTime> ModifiedTime
        {
            get
            {
                return this.ModifiedTimeField;
            }
            set
            {
                this.ModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string ModifiedType
        {
            get
            {
                return this.ModifiedTypeField;
            }
            set
            {
                this.ModifiedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<bool> Multi
        {
            get
            {
                return this.MultiField;
            }
            set
            {
                this.MultiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<bool> Must
        {
            get
            {
                return this.MustField;
            }
            set
            {
                this.MustField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<bool> Required
        {
            get
            {
                return this.RequiredField;
            }
            set
            {
                this.RequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<int> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCat
        {
            get
            {
                return this.ItemCatField;
            }
            set
            {
                this.ItemCatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueList
        {
            get
            {
                return this.PropValueListField;
            }
            set
            {
                this.PropValueListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBItemCatDataObject", Namespace="http://UKjiemeitao.taobao.com/TBItemCatDataObject.xsd")]
    public partial class TBItemCatDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private System.Nullable<long> CidField;
        
        private string NameField;
        
        private System.Nullable<bool> IsParentField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        private string ModifiedTypeField;
        
        private System.Nullable<long> ParentCidField;
        
        private System.Nullable<int> SortOrderField;
        
        private string StatusField;
        
        private UKjiemeitao.Application.DataObjects.TBItemPropDataObjectList ItemPropListField;
        
        private UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this.IsParentField;
            }
            set
            {
                this.IsParentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> ModifiedTime
        {
            get
            {
                return this.ModifiedTimeField;
            }
            set
            {
                this.ModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ModifiedType
        {
            get
            {
                return this.ModifiedTypeField;
            }
            set
            {
                this.ModifiedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<long> ParentCid
        {
            get
            {
                return this.ParentCidField;
            }
            set
            {
                this.ParentCidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public UKjiemeitao.Application.DataObjects.TBItemPropDataObjectList ItemPropList
        {
            get
            {
                return this.ItemPropListField;
            }
            set
            {
                this.ItemPropListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public UKjiemeitao.Application.DataObjects.TBPropValueDataObjectList PropValueList
        {
            get
            {
                return this.PropValueListField;
            }
            set
            {
                this.PropValueListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBPropValueDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBPropValueDataObject")]
    public class TBPropValueDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBPropValueDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBPropValueDataObject", Namespace="http://UKjiemeitao.taobao.com/TBPropValueDataObject.xsd")]
    public partial class TBPropValueDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string ItemCatIDField;
        
        private string ItemPropIDField;
        
        private System.Nullable<long> CidField;
        
        private System.Nullable<bool> IsParentField;
        
        private System.Nullable<System.DateTime> ModifiedTimeField;
        
        private string ModifiedTypeField;
        
        private string NameField;
        
        private string NameAliasField;
        
        private System.Nullable<long> PidField;
        
        private string PropNameField;
        
        private System.Nullable<int> SortOrderField;
        
        private string StatusField;
        
        private System.Nullable<long> VidField;
        
        private UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCatField;
        
        private UKjiemeitao.Application.DataObjects.TBItemPropDataObject ItemPropField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemCatID
        {
            get
            {
                return this.ItemCatIDField;
            }
            set
            {
                this.ItemCatIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemPropID
        {
            get
            {
                return this.ItemPropIDField;
            }
            set
            {
                this.ItemPropIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<long> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this.IsParentField;
            }
            set
            {
                this.IsParentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> ModifiedTime
        {
            get
            {
                return this.ModifiedTimeField;
            }
            set
            {
                this.ModifiedTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ModifiedType
        {
            get
            {
                return this.ModifiedTypeField;
            }
            set
            {
                this.ModifiedTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string NameAlias
        {
            get
            {
                return this.NameAliasField;
            }
            set
            {
                this.NameAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<long> Pid
        {
            get
            {
                return this.PidField;
            }
            set
            {
                this.PidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string PropName
        {
            get
            {
                return this.PropNameField;
            }
            set
            {
                this.PropNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<int> SortOrder
        {
            get
            {
                return this.SortOrderField;
            }
            set
            {
                this.SortOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<long> Vid
        {
            get
            {
                return this.VidField;
            }
            set
            {
                this.VidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public UKjiemeitao.Application.DataObjects.TBItemCatDataObject ItemCat
        {
            get
            {
                return this.ItemCatField;
            }
            set
            {
                this.ItemCatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public UKjiemeitao.Application.DataObjects.TBItemPropDataObject ItemProp
        {
            get
            {
                return this.ItemPropField;
            }
            set
            {
                this.ItemPropField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBItemCatDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBItemCatDataObject")]
    public class TBItemCatDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBItemCatDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TBProductDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="TBProductDataObject")]
    public class TBProductDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.TBProductDataObject>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBProductDataObject", Namespace="http://UKjiemeitao.taobao.com/TBProductDataObject.xsd")]
    public partial class TBProductDataObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDField;
        
        private string TitleField;
        
        private string DescField;
        
        private System.Nullable<decimal> PriceField;
        
        private string StuffStatusField;
        
        private System.Nullable<int> CidField;
        
        private string PropertyAliasField;
        
        private string PropsField;
        
        private string PicPathField;
        
        private System.Nullable<long> NumField;
        
        private string TypeField;
        
        private string LocationStateField;
        
        private string LocationCityField;
        
        private string ApproveStatusField;
        
        private string FreightPayerField;
        
        private System.Nullable<long> ValidThruField;
        
        private System.Nullable<bool> HasInvoiceField;
        
        private System.Nullable<bool> HasWarrantyField;
        
        private System.Nullable<bool> HasShowcaseField;
        
        private string SellerCidsField;
        
        private string InputPidsField;
        
        private string InputStrField;
        
        private System.Nullable<bool> HasDiscountField;
        
        private System.Nullable<decimal> PostFeeField;
        
        private System.Nullable<decimal> ExpressFeeField;
        
        private System.Nullable<decimal> EmsFeeField;
        
        private System.Nullable<System.DateTime> ListTimeField;
        
        private string IncrementField;
        
        private string ImgFilePathField;
        
        private System.Nullable<long> PostageIdField;
        
        private System.Nullable<long> AuctionPointField;
        
        private string SkuPropertiesField;
        
        private string SkuQuantitiesField;
        
        private string SkuPricesField;
        
        private string SkuOuterIdsField;
        
        private string LangField;
        
        private string OuterIdField;
        
        private System.Nullable<bool> IsTaobaoField;
        
        private System.Nullable<bool> IsExField;
        
        private System.Nullable<bool> Is3DField;
        
        private System.Nullable<bool> SellPromiseField;
        
        private System.Nullable<long> AfterSaleIdField;
        
        private System.Nullable<long> CodPostageIdField;
        
        private System.Nullable<bool> IsLightningConsignmentField;
        
        private System.Nullable<long> WeightField;
        
        private System.Nullable<bool> IsXinpinField;
        
        private System.Nullable<long> SubStockField;
        
        private System.Nullable<decimal> ItemSizeField;
        
        private System.Nullable<decimal> ItemWeightField;
        
        private string ChangePropField;
        
        private string DescModulesField;
        
        private string GlobalStockTypeField;
        
        private string GlobalStockCountryField;
        
        private System.Nullable<long> NumIidField;
        
        private System.Nullable<bool> IsReplaceSkuField;
        
        private string EmptyFieldsField;
        
        private System.Nullable<int> StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string StuffStatus
        {
            get
            {
                return this.StuffStatusField;
            }
            set
            {
                this.StuffStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> Cid
        {
            get
            {
                return this.CidField;
            }
            set
            {
                this.CidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string PropertyAlias
        {
            get
            {
                return this.PropertyAliasField;
            }
            set
            {
                this.PropertyAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Props
        {
            get
            {
                return this.PropsField;
            }
            set
            {
                this.PropsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PicPath
        {
            get
            {
                return this.PicPathField;
            }
            set
            {
                this.PicPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<long> Num
        {
            get
            {
                return this.NumField;
            }
            set
            {
                this.NumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string LocationState
        {
            get
            {
                return this.LocationStateField;
            }
            set
            {
                this.LocationStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string LocationCity
        {
            get
            {
                return this.LocationCityField;
            }
            set
            {
                this.LocationCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string ApproveStatus
        {
            get
            {
                return this.ApproveStatusField;
            }
            set
            {
                this.ApproveStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string FreightPayer
        {
            get
            {
                return this.FreightPayerField;
            }
            set
            {
                this.FreightPayerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<long> ValidThru
        {
            get
            {
                return this.ValidThruField;
            }
            set
            {
                this.ValidThruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<bool> HasInvoice
        {
            get
            {
                return this.HasInvoiceField;
            }
            set
            {
                this.HasInvoiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.Nullable<bool> HasWarranty
        {
            get
            {
                return this.HasWarrantyField;
            }
            set
            {
                this.HasWarrantyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<bool> HasShowcase
        {
            get
            {
                return this.HasShowcaseField;
            }
            set
            {
                this.HasShowcaseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string SellerCids
        {
            get
            {
                return this.SellerCidsField;
            }
            set
            {
                this.SellerCidsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string InputPids
        {
            get
            {
                return this.InputPidsField;
            }
            set
            {
                this.InputPidsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string InputStr
        {
            get
            {
                return this.InputStrField;
            }
            set
            {
                this.InputStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<bool> HasDiscount
        {
            get
            {
                return this.HasDiscountField;
            }
            set
            {
                this.HasDiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public System.Nullable<decimal> PostFee
        {
            get
            {
                return this.PostFeeField;
            }
            set
            {
                this.PostFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<decimal> ExpressFee
        {
            get
            {
                return this.ExpressFeeField;
            }
            set
            {
                this.ExpressFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<decimal> EmsFee
        {
            get
            {
                return this.EmsFeeField;
            }
            set
            {
                this.EmsFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<System.DateTime> ListTime
        {
            get
            {
                return this.ListTimeField;
            }
            set
            {
                this.ListTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string Increment
        {
            get
            {
                return this.IncrementField;
            }
            set
            {
                this.IncrementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string ImgFilePath
        {
            get
            {
                return this.ImgFilePathField;
            }
            set
            {
                this.ImgFilePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public System.Nullable<long> PostageId
        {
            get
            {
                return this.PostageIdField;
            }
            set
            {
                this.PostageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public System.Nullable<long> AuctionPoint
        {
            get
            {
                return this.AuctionPointField;
            }
            set
            {
                this.AuctionPointField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string SkuProperties
        {
            get
            {
                return this.SkuPropertiesField;
            }
            set
            {
                this.SkuPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public string SkuQuantities
        {
            get
            {
                return this.SkuQuantitiesField;
            }
            set
            {
                this.SkuQuantitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public string SkuPrices
        {
            get
            {
                return this.SkuPricesField;
            }
            set
            {
                this.SkuPricesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public string SkuOuterIds
        {
            get
            {
                return this.SkuOuterIdsField;
            }
            set
            {
                this.SkuOuterIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public string OuterId
        {
            get
            {
                return this.OuterIdField;
            }
            set
            {
                this.OuterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public System.Nullable<bool> IsTaobao
        {
            get
            {
                return this.IsTaobaoField;
            }
            set
            {
                this.IsTaobaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public System.Nullable<bool> IsEx
        {
            get
            {
                return this.IsExField;
            }
            set
            {
                this.IsExField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public System.Nullable<bool> Is3D
        {
            get
            {
                return this.Is3DField;
            }
            set
            {
                this.Is3DField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public System.Nullable<bool> SellPromise
        {
            get
            {
                return this.SellPromiseField;
            }
            set
            {
                this.SellPromiseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public System.Nullable<long> AfterSaleId
        {
            get
            {
                return this.AfterSaleIdField;
            }
            set
            {
                this.AfterSaleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public System.Nullable<long> CodPostageId
        {
            get
            {
                return this.CodPostageIdField;
            }
            set
            {
                this.CodPostageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public System.Nullable<bool> IsLightningConsignment
        {
            get
            {
                return this.IsLightningConsignmentField;
            }
            set
            {
                this.IsLightningConsignmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public System.Nullable<long> Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public System.Nullable<bool> IsXinpin
        {
            get
            {
                return this.IsXinpinField;
            }
            set
            {
                this.IsXinpinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public System.Nullable<long> SubStock
        {
            get
            {
                return this.SubStockField;
            }
            set
            {
                this.SubStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public System.Nullable<decimal> ItemSize
        {
            get
            {
                return this.ItemSizeField;
            }
            set
            {
                this.ItemSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public System.Nullable<decimal> ItemWeight
        {
            get
            {
                return this.ItemWeightField;
            }
            set
            {
                this.ItemWeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public string ChangeProp
        {
            get
            {
                return this.ChangePropField;
            }
            set
            {
                this.ChangePropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public string DescModules
        {
            get
            {
                return this.DescModulesField;
            }
            set
            {
                this.DescModulesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=51)]
        public string GlobalStockType
        {
            get
            {
                return this.GlobalStockTypeField;
            }
            set
            {
                this.GlobalStockTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=52)]
        public string GlobalStockCountry
        {
            get
            {
                return this.GlobalStockCountryField;
            }
            set
            {
                this.GlobalStockCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=53)]
        public System.Nullable<long> NumIid
        {
            get
            {
                return this.NumIidField;
            }
            set
            {
                this.NumIidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=54)]
        public System.Nullable<bool> IsReplaceSku
        {
            get
            {
                return this.IsReplaceSkuField;
            }
            set
            {
                this.IsReplaceSkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=55)]
        public string EmptyFields
        {
            get
            {
                return this.EmptyFieldsField;
            }
            set
            {
                this.EmptyFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=56)]
        public System.Nullable<int> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SSTBBrandMappingDataObjectList", Namespace="http://UKjiemeitao.taobao.com/TBCollectionDataObjectList.xsd", ItemName="SSTBBrandMappingDataObject")]
    public class SSTBBrandMappingDataObjectList : System.Collections.Generic.List<UKjiemeitao.Application.DataObjects.SSTBBrandMappingDataObject>
    {
    }
}
