#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaoBaoAPIClient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Catalog")]
	public partial class TaoBaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_ItemCat(TB_ItemCat instance);
    partial void UpdateTB_ItemCat(TB_ItemCat instance);
    partial void DeleteTB_ItemCat(TB_ItemCat instance);
    partial void InsertTB_ItemProp(TB_ItemProp instance);
    partial void UpdateTB_ItemProp(TB_ItemProp instance);
    partial void DeleteTB_ItemProp(TB_ItemProp instance);
    partial void InsertTB_Product(TB_Product instance);
    partial void UpdateTB_Product(TB_Product instance);
    partial void DeleteTB_Product(TB_Product instance);
    partial void InsertTB_PropValue(TB_PropValue instance);
    partial void UpdateTB_PropValue(TB_PropValue instance);
    partial void DeleteTB_PropValue(TB_PropValue instance);
    #endregion
		
		public TaoBaoDataContext() : 
				base(global::TaoBaoAPIClient.Properties.Settings.Default.CatalogConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TaoBaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_ItemCat> TB_ItemCats
		{
			get
			{
				return this.GetTable<TB_ItemCat>();
			}
		}
		
		public System.Data.Linq.Table<TB_ItemProp> TB_ItemProps
		{
			get
			{
				return this.GetTable<TB_ItemProp>();
			}
		}
		
		public System.Data.Linq.Table<TB_Product> TB_Products
		{
			get
			{
				return this.GetTable<TB_Product>();
			}
		}
		
		public System.Data.Linq.Table<TB_PropValue> TB_PropValues
		{
			get
			{
				return this.GetTable<TB_PropValue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ItemCat")]
	public partial class TB_ItemCat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private long _Cid;
		
		private string _Name;
		
		private System.Nullable<bool> _IsParent;
		
		private System.Nullable<System.DateTime> _ModifiedTime;
		
		private string _ModifiedType;
		
		private System.Nullable<long> _ParentCid;
		
		private System.Nullable<long> _SortOrder;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCidChanging(long value);
    partial void OnCidChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIsParentChanging(System.Nullable<bool> value);
    partial void OnIsParentChanged();
    partial void OnModifiedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedTimeChanged();
    partial void OnModifiedTypeChanging(string value);
    partial void OnModifiedTypeChanged();
    partial void OnParentCidChanging(System.Nullable<long> value);
    partial void OnParentCidChanged();
    partial void OnSortOrderChanging(System.Nullable<long> value);
    partial void OnSortOrderChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public TB_ItemCat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="BigInt NOT NULL")]
		public long Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="Bit")]
		public System.Nullable<bool> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedTime
		{
			get
			{
				return this._ModifiedTime;
			}
			set
			{
				if ((this._ModifiedTime != value))
				{
					this.OnModifiedTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedTime = value;
					this.SendPropertyChanged("ModifiedTime");
					this.OnModifiedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedType", DbType="NChar(50)")]
		public string ModifiedType
		{
			get
			{
				return this._ModifiedType;
			}
			set
			{
				if ((this._ModifiedType != value))
				{
					this.OnModifiedTypeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedType = value;
					this.SendPropertyChanged("ModifiedType");
					this.OnModifiedTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCid", DbType="BigInt")]
		public System.Nullable<long> ParentCid
		{
			get
			{
				return this._ParentCid;
			}
			set
			{
				if ((this._ParentCid != value))
				{
					this.OnParentCidChanging(value);
					this.SendPropertyChanging();
					this._ParentCid = value;
					this.SendPropertyChanged("ParentCid");
					this.OnParentCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="BigInt")]
		public System.Nullable<long> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_ItemProp")]
	public partial class TB_ItemProp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<long> _Cid;
		
		private System.Nullable<long> _Pid;
		
		private System.Nullable<long> _ParentPid;
		
		private System.Nullable<long> _ParentVid;
		
		private string _ChildTemplate;
		
		private System.Nullable<bool> _IsAllowAlias;
		
		private System.Nullable<bool> _IsColorProp;
		
		private System.Nullable<bool> _IsEnumProp;
		
		private System.Nullable<bool> _IsInputProp;
		
		private System.Nullable<bool> _IsItemProp;
		
		private System.Nullable<bool> _IsKeyProp;
		
		private System.Nullable<bool> _IsSaleProp;
		
		private System.Nullable<System.DateTime> _ModifiedTime;
		
		private string _ModifiedType;
		
		private System.Nullable<bool> _Multi;
		
		private System.Nullable<bool> _Must;
		
		private string _Name;
		
		private System.Nullable<bool> _Required;
		
		private System.Nullable<long> _SortOrder;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCidChanging(System.Nullable<long> value);
    partial void OnCidChanged();
    partial void OnPidChanging(System.Nullable<long> value);
    partial void OnPidChanged();
    partial void OnParentPidChanging(System.Nullable<long> value);
    partial void OnParentPidChanged();
    partial void OnParentVidChanging(System.Nullable<long> value);
    partial void OnParentVidChanged();
    partial void OnChildTemplateChanging(string value);
    partial void OnChildTemplateChanged();
    partial void OnIsAllowAliasChanging(System.Nullable<bool> value);
    partial void OnIsAllowAliasChanged();
    partial void OnIsColorPropChanging(System.Nullable<bool> value);
    partial void OnIsColorPropChanged();
    partial void OnIsEnumPropChanging(System.Nullable<bool> value);
    partial void OnIsEnumPropChanged();
    partial void OnIsInputPropChanging(System.Nullable<bool> value);
    partial void OnIsInputPropChanged();
    partial void OnIsItemPropChanging(System.Nullable<bool> value);
    partial void OnIsItemPropChanged();
    partial void OnIsKeyPropChanging(System.Nullable<bool> value);
    partial void OnIsKeyPropChanged();
    partial void OnIsSalePropChanging(System.Nullable<bool> value);
    partial void OnIsSalePropChanged();
    partial void OnModifiedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedTimeChanged();
    partial void OnModifiedTypeChanging(string value);
    partial void OnModifiedTypeChanged();
    partial void OnMultiChanging(System.Nullable<bool> value);
    partial void OnMultiChanged();
    partial void OnMustChanging(System.Nullable<bool> value);
    partial void OnMustChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRequiredChanging(System.Nullable<bool> value);
    partial void OnRequiredChanged();
    partial void OnSortOrderChanging(System.Nullable<long> value);
    partial void OnSortOrderChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public TB_ItemProp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="BigInt")]
		public System.Nullable<long> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="BigInt")]
		public System.Nullable<long> Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentPid", DbType="BigInt")]
		public System.Nullable<long> ParentPid
		{
			get
			{
				return this._ParentPid;
			}
			set
			{
				if ((this._ParentPid != value))
				{
					this.OnParentPidChanging(value);
					this.SendPropertyChanging();
					this._ParentPid = value;
					this.SendPropertyChanged("ParentPid");
					this.OnParentPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentVid", DbType="BigInt")]
		public System.Nullable<long> ParentVid
		{
			get
			{
				return this._ParentVid;
			}
			set
			{
				if ((this._ParentVid != value))
				{
					this.OnParentVidChanging(value);
					this.SendPropertyChanging();
					this._ParentVid = value;
					this.SendPropertyChanged("ParentVid");
					this.OnParentVidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildTemplate", DbType="NVarChar(2000)")]
		public string ChildTemplate
		{
			get
			{
				return this._ChildTemplate;
			}
			set
			{
				if ((this._ChildTemplate != value))
				{
					this.OnChildTemplateChanging(value);
					this.SendPropertyChanging();
					this._ChildTemplate = value;
					this.SendPropertyChanged("ChildTemplate");
					this.OnChildTemplateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAllowAlias", DbType="Bit")]
		public System.Nullable<bool> IsAllowAlias
		{
			get
			{
				return this._IsAllowAlias;
			}
			set
			{
				if ((this._IsAllowAlias != value))
				{
					this.OnIsAllowAliasChanging(value);
					this.SendPropertyChanging();
					this._IsAllowAlias = value;
					this.SendPropertyChanged("IsAllowAlias");
					this.OnIsAllowAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsColorProp", DbType="Bit")]
		public System.Nullable<bool> IsColorProp
		{
			get
			{
				return this._IsColorProp;
			}
			set
			{
				if ((this._IsColorProp != value))
				{
					this.OnIsColorPropChanging(value);
					this.SendPropertyChanging();
					this._IsColorProp = value;
					this.SendPropertyChanged("IsColorProp");
					this.OnIsColorPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEnumProp", DbType="Bit")]
		public System.Nullable<bool> IsEnumProp
		{
			get
			{
				return this._IsEnumProp;
			}
			set
			{
				if ((this._IsEnumProp != value))
				{
					this.OnIsEnumPropChanging(value);
					this.SendPropertyChanging();
					this._IsEnumProp = value;
					this.SendPropertyChanged("IsEnumProp");
					this.OnIsEnumPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInputProp", DbType="Bit")]
		public System.Nullable<bool> IsInputProp
		{
			get
			{
				return this._IsInputProp;
			}
			set
			{
				if ((this._IsInputProp != value))
				{
					this.OnIsInputPropChanging(value);
					this.SendPropertyChanging();
					this._IsInputProp = value;
					this.SendPropertyChanged("IsInputProp");
					this.OnIsInputPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsItemProp", DbType="Bit")]
		public System.Nullable<bool> IsItemProp
		{
			get
			{
				return this._IsItemProp;
			}
			set
			{
				if ((this._IsItemProp != value))
				{
					this.OnIsItemPropChanging(value);
					this.SendPropertyChanging();
					this._IsItemProp = value;
					this.SendPropertyChanged("IsItemProp");
					this.OnIsItemPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsKeyProp", DbType="Bit")]
		public System.Nullable<bool> IsKeyProp
		{
			get
			{
				return this._IsKeyProp;
			}
			set
			{
				if ((this._IsKeyProp != value))
				{
					this.OnIsKeyPropChanging(value);
					this.SendPropertyChanging();
					this._IsKeyProp = value;
					this.SendPropertyChanged("IsKeyProp");
					this.OnIsKeyPropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSaleProp", DbType="Bit")]
		public System.Nullable<bool> IsSaleProp
		{
			get
			{
				return this._IsSaleProp;
			}
			set
			{
				if ((this._IsSaleProp != value))
				{
					this.OnIsSalePropChanging(value);
					this.SendPropertyChanging();
					this._IsSaleProp = value;
					this.SendPropertyChanged("IsSaleProp");
					this.OnIsSalePropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedTime
		{
			get
			{
				return this._ModifiedTime;
			}
			set
			{
				if ((this._ModifiedTime != value))
				{
					this.OnModifiedTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedTime = value;
					this.SendPropertyChanged("ModifiedTime");
					this.OnModifiedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedType", DbType="NChar(50)")]
		public string ModifiedType
		{
			get
			{
				return this._ModifiedType;
			}
			set
			{
				if ((this._ModifiedType != value))
				{
					this.OnModifiedTypeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedType = value;
					this.SendPropertyChanged("ModifiedType");
					this.OnModifiedTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Multi", DbType="Bit")]
		public System.Nullable<bool> Multi
		{
			get
			{
				return this._Multi;
			}
			set
			{
				if ((this._Multi != value))
				{
					this.OnMultiChanging(value);
					this.SendPropertyChanging();
					this._Multi = value;
					this.SendPropertyChanged("Multi");
					this.OnMultiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Must", DbType="Bit")]
		public System.Nullable<bool> Must
		{
			get
			{
				return this._Must;
			}
			set
			{
				if ((this._Must != value))
				{
					this.OnMustChanging(value);
					this.SendPropertyChanging();
					this._Must = value;
					this.SendPropertyChanged("Must");
					this.OnMustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Required", DbType="Bit")]
		public System.Nullable<bool> Required
		{
			get
			{
				return this._Required;
			}
			set
			{
				if ((this._Required != value))
				{
					this.OnRequiredChanging(value);
					this.SendPropertyChanging();
					this._Required = value;
					this.SendPropertyChanged("Required");
					this.OnRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="BigInt")]
		public System.Nullable<long> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Product")]
	public partial class TB_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Title;
		
		private string _Desc;
		
		private System.Nullable<decimal> _Price;
		
		private string _StuffStatus;
		
		private System.Nullable<long> _Cid;
		
		private string _PropertyAlias;
		
		private string _Props;
		
		private string _PicPath;
		
		private System.Nullable<long> _Num;
		
		private string _Type;
		
		private string _LocationState;
		
		private string _LocationCity;
		
		private string _ApproveStatus;
		
		private string _FreightPayer;
		
		private System.Nullable<long> _ValidThru;
		
		private System.Nullable<bool> _HasInvoice;
		
		private System.Nullable<bool> _HasWarranty;
		
		private System.Nullable<bool> _HasShowcase;
		
		private string _SellerCids;
		
		private string _InputPids;
		
		private string _InputStr;
		
		private System.Nullable<bool> _HasDiscount;
		
		private System.Nullable<decimal> _PostFee;
		
		private System.Nullable<decimal> _ExpressFee;
		
		private System.Nullable<decimal> _EmsFee;
		
		private System.Nullable<System.DateTime> _ListTime;
		
		private string _Increment;
		
		private string _ImgFilePath;
		
		private System.Nullable<long> _PostageId;
		
		private System.Nullable<long> _AuctionPoint;
		
		private string _SkuProperties;
		
		private string _SkuQuantities;
		
		private string _SkuPrices;
		
		private string _SkuOuterIds;
		
		private string _Lang;
		
		private string _OuterId;
		
		private System.Nullable<bool> _IsTaobao;
		
		private System.Nullable<bool> _IsEx;
		
		private System.Nullable<bool> _Is3D;
		
		private System.Nullable<bool> _SellPromise;
		
		private System.Nullable<long> _AfterSaleId;
		
		private System.Nullable<long> _CodPostageId;
		
		private System.Nullable<bool> _IsLightningConsignment;
		
		private System.Nullable<long> _Weight;
		
		private System.Nullable<bool> _IsXinpin;
		
		private System.Nullable<long> _SubStock;
		
		private System.Nullable<decimal> _ItemSize;
		
		private System.Nullable<decimal> _ItemWeight;
		
		private string _ChangeProp;
		
		private string _DescModules;
		
		private string _GlobalStockType;
		
		private string _GlobalStockCountry;
		
		private System.Nullable<long> _NumIid;
		
		private System.Nullable<bool> _IsReplaceSku;
		
		private string _EmptyFields;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<long> _SSProductID;
		
		private System.Nullable<bool> _IsUploaded;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescChanging(string value);
    partial void OnDescChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnStuffStatusChanging(string value);
    partial void OnStuffStatusChanged();
    partial void OnCidChanging(System.Nullable<long> value);
    partial void OnCidChanged();
    partial void OnPropertyAliasChanging(string value);
    partial void OnPropertyAliasChanged();
    partial void OnPropsChanging(string value);
    partial void OnPropsChanged();
    partial void OnPicPathChanging(string value);
    partial void OnPicPathChanged();
    partial void OnNumChanging(System.Nullable<long> value);
    partial void OnNumChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnLocationStateChanging(string value);
    partial void OnLocationStateChanged();
    partial void OnLocationCityChanging(string value);
    partial void OnLocationCityChanged();
    partial void OnApproveStatusChanging(string value);
    partial void OnApproveStatusChanged();
    partial void OnFreightPayerChanging(string value);
    partial void OnFreightPayerChanged();
    partial void OnValidThruChanging(System.Nullable<long> value);
    partial void OnValidThruChanged();
    partial void OnHasInvoiceChanging(System.Nullable<bool> value);
    partial void OnHasInvoiceChanged();
    partial void OnHasWarrantyChanging(System.Nullable<bool> value);
    partial void OnHasWarrantyChanged();
    partial void OnHasShowcaseChanging(System.Nullable<bool> value);
    partial void OnHasShowcaseChanged();
    partial void OnSellerCidsChanging(string value);
    partial void OnSellerCidsChanged();
    partial void OnInputPidsChanging(string value);
    partial void OnInputPidsChanged();
    partial void OnInputStrChanging(string value);
    partial void OnInputStrChanged();
    partial void OnHasDiscountChanging(System.Nullable<bool> value);
    partial void OnHasDiscountChanged();
    partial void OnPostFeeChanging(System.Nullable<decimal> value);
    partial void OnPostFeeChanged();
    partial void OnExpressFeeChanging(System.Nullable<decimal> value);
    partial void OnExpressFeeChanged();
    partial void OnEmsFeeChanging(System.Nullable<decimal> value);
    partial void OnEmsFeeChanged();
    partial void OnListTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnListTimeChanged();
    partial void OnIncrementChanging(string value);
    partial void OnIncrementChanged();
    partial void OnImgFilePathChanging(string value);
    partial void OnImgFilePathChanged();
    partial void OnPostageIdChanging(System.Nullable<long> value);
    partial void OnPostageIdChanged();
    partial void OnAuctionPointChanging(System.Nullable<long> value);
    partial void OnAuctionPointChanged();
    partial void OnSkuPropertiesChanging(string value);
    partial void OnSkuPropertiesChanged();
    partial void OnSkuQuantitiesChanging(string value);
    partial void OnSkuQuantitiesChanged();
    partial void OnSkuPricesChanging(string value);
    partial void OnSkuPricesChanged();
    partial void OnSkuOuterIdsChanging(string value);
    partial void OnSkuOuterIdsChanged();
    partial void OnLangChanging(string value);
    partial void OnLangChanged();
    partial void OnOuterIdChanging(string value);
    partial void OnOuterIdChanged();
    partial void OnIsTaobaoChanging(System.Nullable<bool> value);
    partial void OnIsTaobaoChanged();
    partial void OnIsExChanging(System.Nullable<bool> value);
    partial void OnIsExChanged();
    partial void OnIs3DChanging(System.Nullable<bool> value);
    partial void OnIs3DChanged();
    partial void OnSellPromiseChanging(System.Nullable<bool> value);
    partial void OnSellPromiseChanged();
    partial void OnAfterSaleIdChanging(System.Nullable<long> value);
    partial void OnAfterSaleIdChanged();
    partial void OnCodPostageIdChanging(System.Nullable<long> value);
    partial void OnCodPostageIdChanged();
    partial void OnIsLightningConsignmentChanging(System.Nullable<bool> value);
    partial void OnIsLightningConsignmentChanged();
    partial void OnWeightChanging(System.Nullable<long> value);
    partial void OnWeightChanged();
    partial void OnIsXinpinChanging(System.Nullable<bool> value);
    partial void OnIsXinpinChanged();
    partial void OnSubStockChanging(System.Nullable<long> value);
    partial void OnSubStockChanged();
    partial void OnItemSizeChanging(System.Nullable<decimal> value);
    partial void OnItemSizeChanged();
    partial void OnItemWeightChanging(System.Nullable<decimal> value);
    partial void OnItemWeightChanged();
    partial void OnChangePropChanging(string value);
    partial void OnChangePropChanged();
    partial void OnDescModulesChanging(string value);
    partial void OnDescModulesChanged();
    partial void OnGlobalStockTypeChanging(string value);
    partial void OnGlobalStockTypeChanged();
    partial void OnGlobalStockCountryChanging(string value);
    partial void OnGlobalStockCountryChanged();
    partial void OnNumIidChanging(System.Nullable<long> value);
    partial void OnNumIidChanged();
    partial void OnIsReplaceSkuChanging(System.Nullable<bool> value);
    partial void OnIsReplaceSkuChanged();
    partial void OnEmptyFieldsChanging(string value);
    partial void OnEmptyFieldsChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    partial void OnSSProductIDChanging(System.Nullable<long> value);
    partial void OnSSProductIDChanged();
    partial void OnIsUploadedChanging(System.Nullable<bool> value);
    partial void OnIsUploadedChanged();
    #endregion
		
		public TB_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(30)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this.OnDescChanging(value);
					this.SendPropertyChanging();
					this._Desc = value;
					this.SendPropertyChanged("Desc");
					this.OnDescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StuffStatus", DbType="VarChar(50)")]
		public string StuffStatus
		{
			get
			{
				return this._StuffStatus;
			}
			set
			{
				if ((this._StuffStatus != value))
				{
					this.OnStuffStatusChanging(value);
					this.SendPropertyChanging();
					this._StuffStatus = value;
					this.SendPropertyChanged("StuffStatus");
					this.OnStuffStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="BigInt")]
		public System.Nullable<long> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyAlias", DbType="NVarChar(511)")]
		public string PropertyAlias
		{
			get
			{
				return this._PropertyAlias;
			}
			set
			{
				if ((this._PropertyAlias != value))
				{
					this.OnPropertyAliasChanging(value);
					this.SendPropertyChanging();
					this._PropertyAlias = value;
					this.SendPropertyChanged("PropertyAlias");
					this.OnPropertyAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Props", DbType="NVarChar(549)")]
		public string Props
		{
			get
			{
				return this._Props;
			}
			set
			{
				if ((this._Props != value))
				{
					this.OnPropsChanging(value);
					this.SendPropertyChanging();
					this._Props = value;
					this.SendPropertyChanged("Props");
					this.OnPropsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicPath", DbType="NChar(1000)")]
		public string PicPath
		{
			get
			{
				return this._PicPath;
			}
			set
			{
				if ((this._PicPath != value))
				{
					this.OnPicPathChanging(value);
					this.SendPropertyChanging();
					this._PicPath = value;
					this.SendPropertyChanged("PicPath");
					this.OnPicPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num", DbType="BigInt")]
		public System.Nullable<long> Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this.OnNumChanging(value);
					this.SendPropertyChanging();
					this._Num = value;
					this.SendPropertyChanged("Num");
					this.OnNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationState", DbType="NVarChar(100)")]
		public string LocationState
		{
			get
			{
				return this._LocationState;
			}
			set
			{
				if ((this._LocationState != value))
				{
					this.OnLocationStateChanging(value);
					this.SendPropertyChanging();
					this._LocationState = value;
					this.SendPropertyChanged("LocationState");
					this.OnLocationStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCity", DbType="NVarChar(100)")]
		public string LocationCity
		{
			get
			{
				return this._LocationCity;
			}
			set
			{
				if ((this._LocationCity != value))
				{
					this.OnLocationCityChanging(value);
					this.SendPropertyChanging();
					this._LocationCity = value;
					this.SendPropertyChanged("LocationCity");
					this.OnLocationCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApproveStatus", DbType="VarChar(50)")]
		public string ApproveStatus
		{
			get
			{
				return this._ApproveStatus;
			}
			set
			{
				if ((this._ApproveStatus != value))
				{
					this.OnApproveStatusChanging(value);
					this.SendPropertyChanging();
					this._ApproveStatus = value;
					this.SendPropertyChanged("ApproveStatus");
					this.OnApproveStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FreightPayer", DbType="VarChar(50)")]
		public string FreightPayer
		{
			get
			{
				return this._FreightPayer;
			}
			set
			{
				if ((this._FreightPayer != value))
				{
					this.OnFreightPayerChanging(value);
					this.SendPropertyChanging();
					this._FreightPayer = value;
					this.SendPropertyChanged("FreightPayer");
					this.OnFreightPayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidThru", DbType="BigInt")]
		public System.Nullable<long> ValidThru
		{
			get
			{
				return this._ValidThru;
			}
			set
			{
				if ((this._ValidThru != value))
				{
					this.OnValidThruChanging(value);
					this.SendPropertyChanging();
					this._ValidThru = value;
					this.SendPropertyChanged("ValidThru");
					this.OnValidThruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasInvoice", DbType="Bit")]
		public System.Nullable<bool> HasInvoice
		{
			get
			{
				return this._HasInvoice;
			}
			set
			{
				if ((this._HasInvoice != value))
				{
					this.OnHasInvoiceChanging(value);
					this.SendPropertyChanging();
					this._HasInvoice = value;
					this.SendPropertyChanged("HasInvoice");
					this.OnHasInvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasWarranty", DbType="Bit")]
		public System.Nullable<bool> HasWarranty
		{
			get
			{
				return this._HasWarranty;
			}
			set
			{
				if ((this._HasWarranty != value))
				{
					this.OnHasWarrantyChanging(value);
					this.SendPropertyChanging();
					this._HasWarranty = value;
					this.SendPropertyChanged("HasWarranty");
					this.OnHasWarrantyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasShowcase", DbType="Bit")]
		public System.Nullable<bool> HasShowcase
		{
			get
			{
				return this._HasShowcase;
			}
			set
			{
				if ((this._HasShowcase != value))
				{
					this.OnHasShowcaseChanging(value);
					this.SendPropertyChanging();
					this._HasShowcase = value;
					this.SendPropertyChanged("HasShowcase");
					this.OnHasShowcaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellerCids", DbType="NVarChar(200)")]
		public string SellerCids
		{
			get
			{
				return this._SellerCids;
			}
			set
			{
				if ((this._SellerCids != value))
				{
					this.OnSellerCidsChanging(value);
					this.SendPropertyChanging();
					this._SellerCids = value;
					this.SendPropertyChanged("SellerCids");
					this.OnSellerCidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputPids", DbType="NVarChar(200)")]
		public string InputPids
		{
			get
			{
				return this._InputPids;
			}
			set
			{
				if ((this._InputPids != value))
				{
					this.OnInputPidsChanging(value);
					this.SendPropertyChanging();
					this._InputPids = value;
					this.SendPropertyChanged("InputPids");
					this.OnInputPidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputStr", DbType="NVarChar(200)")]
		public string InputStr
		{
			get
			{
				return this._InputStr;
			}
			set
			{
				if ((this._InputStr != value))
				{
					this.OnInputStrChanging(value);
					this.SendPropertyChanging();
					this._InputStr = value;
					this.SendPropertyChanged("InputStr");
					this.OnInputStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasDiscount", DbType="Bit")]
		public System.Nullable<bool> HasDiscount
		{
			get
			{
				return this._HasDiscount;
			}
			set
			{
				if ((this._HasDiscount != value))
				{
					this.OnHasDiscountChanging(value);
					this.SendPropertyChanging();
					this._HasDiscount = value;
					this.SendPropertyChanged("HasDiscount");
					this.OnHasDiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostFee", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> PostFee
		{
			get
			{
				return this._PostFee;
			}
			set
			{
				if ((this._PostFee != value))
				{
					this.OnPostFeeChanging(value);
					this.SendPropertyChanging();
					this._PostFee = value;
					this.SendPropertyChanged("PostFee");
					this.OnPostFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpressFee", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> ExpressFee
		{
			get
			{
				return this._ExpressFee;
			}
			set
			{
				if ((this._ExpressFee != value))
				{
					this.OnExpressFeeChanging(value);
					this.SendPropertyChanging();
					this._ExpressFee = value;
					this.SendPropertyChanged("ExpressFee");
					this.OnExpressFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmsFee", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> EmsFee
		{
			get
			{
				return this._EmsFee;
			}
			set
			{
				if ((this._EmsFee != value))
				{
					this.OnEmsFeeChanging(value);
					this.SendPropertyChanging();
					this._EmsFee = value;
					this.SendPropertyChanged("EmsFee");
					this.OnEmsFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ListTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ListTime
		{
			get
			{
				return this._ListTime;
			}
			set
			{
				if ((this._ListTime != value))
				{
					this.OnListTimeChanging(value);
					this.SendPropertyChanging();
					this._ListTime = value;
					this.SendPropertyChanged("ListTime");
					this.OnListTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Increment", DbType="NVarChar(50)")]
		public string Increment
		{
			get
			{
				return this._Increment;
			}
			set
			{
				if ((this._Increment != value))
				{
					this.OnIncrementChanging(value);
					this.SendPropertyChanging();
					this._Increment = value;
					this.SendPropertyChanged("Increment");
					this.OnIncrementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImgFilePath", DbType="NVarChar(256)")]
		public string ImgFilePath
		{
			get
			{
				return this._ImgFilePath;
			}
			set
			{
				if ((this._ImgFilePath != value))
				{
					this.OnImgFilePathChanging(value);
					this.SendPropertyChanging();
					this._ImgFilePath = value;
					this.SendPropertyChanged("ImgFilePath");
					this.OnImgFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostageId", DbType="BigInt")]
		public System.Nullable<long> PostageId
		{
			get
			{
				return this._PostageId;
			}
			set
			{
				if ((this._PostageId != value))
				{
					this.OnPostageIdChanging(value);
					this.SendPropertyChanging();
					this._PostageId = value;
					this.SendPropertyChanged("PostageId");
					this.OnPostageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuctionPoint", DbType="BigInt")]
		public System.Nullable<long> AuctionPoint
		{
			get
			{
				return this._AuctionPoint;
			}
			set
			{
				if ((this._AuctionPoint != value))
				{
					this.OnAuctionPointChanging(value);
					this.SendPropertyChanging();
					this._AuctionPoint = value;
					this.SendPropertyChanged("AuctionPoint");
					this.OnAuctionPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkuProperties", DbType="NVarChar(4000)")]
		public string SkuProperties
		{
			get
			{
				return this._SkuProperties;
			}
			set
			{
				if ((this._SkuProperties != value))
				{
					this.OnSkuPropertiesChanging(value);
					this.SendPropertyChanging();
					this._SkuProperties = value;
					this.SendPropertyChanged("SkuProperties");
					this.OnSkuPropertiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkuQuantities", DbType="NVarChar(4000)")]
		public string SkuQuantities
		{
			get
			{
				return this._SkuQuantities;
			}
			set
			{
				if ((this._SkuQuantities != value))
				{
					this.OnSkuQuantitiesChanging(value);
					this.SendPropertyChanging();
					this._SkuQuantities = value;
					this.SendPropertyChanged("SkuQuantities");
					this.OnSkuQuantitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkuPrices", DbType="NVarChar(4000)")]
		public string SkuPrices
		{
			get
			{
				return this._SkuPrices;
			}
			set
			{
				if ((this._SkuPrices != value))
				{
					this.OnSkuPricesChanging(value);
					this.SendPropertyChanging();
					this._SkuPrices = value;
					this.SendPropertyChanged("SkuPrices");
					this.OnSkuPricesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SkuOuterIds", DbType="NVarChar(4000)")]
		public string SkuOuterIds
		{
			get
			{
				return this._SkuOuterIds;
			}
			set
			{
				if ((this._SkuOuterIds != value))
				{
					this.OnSkuOuterIdsChanging(value);
					this.SendPropertyChanging();
					this._SkuOuterIds = value;
					this.SendPropertyChanged("SkuOuterIds");
					this.OnSkuOuterIdsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lang", DbType="NVarChar(50)")]
		public string Lang
		{
			get
			{
				return this._Lang;
			}
			set
			{
				if ((this._Lang != value))
				{
					this.OnLangChanging(value);
					this.SendPropertyChanging();
					this._Lang = value;
					this.SendPropertyChanged("Lang");
					this.OnLangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OuterId", DbType="NVarChar(512)")]
		public string OuterId
		{
			get
			{
				return this._OuterId;
			}
			set
			{
				if ((this._OuterId != value))
				{
					this.OnOuterIdChanging(value);
					this.SendPropertyChanging();
					this._OuterId = value;
					this.SendPropertyChanged("OuterId");
					this.OnOuterIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTaobao", DbType="Bit")]
		public System.Nullable<bool> IsTaobao
		{
			get
			{
				return this._IsTaobao;
			}
			set
			{
				if ((this._IsTaobao != value))
				{
					this.OnIsTaobaoChanging(value);
					this.SendPropertyChanging();
					this._IsTaobao = value;
					this.SendPropertyChanged("IsTaobao");
					this.OnIsTaobaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEx", DbType="Bit")]
		public System.Nullable<bool> IsEx
		{
			get
			{
				return this._IsEx;
			}
			set
			{
				if ((this._IsEx != value))
				{
					this.OnIsExChanging(value);
					this.SendPropertyChanging();
					this._IsEx = value;
					this.SendPropertyChanged("IsEx");
					this.OnIsExChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is3D", DbType="Bit")]
		public System.Nullable<bool> Is3D
		{
			get
			{
				return this._Is3D;
			}
			set
			{
				if ((this._Is3D != value))
				{
					this.OnIs3DChanging(value);
					this.SendPropertyChanging();
					this._Is3D = value;
					this.SendPropertyChanged("Is3D");
					this.OnIs3DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellPromise", DbType="Bit")]
		public System.Nullable<bool> SellPromise
		{
			get
			{
				return this._SellPromise;
			}
			set
			{
				if ((this._SellPromise != value))
				{
					this.OnSellPromiseChanging(value);
					this.SendPropertyChanging();
					this._SellPromise = value;
					this.SendPropertyChanged("SellPromise");
					this.OnSellPromiseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AfterSaleId", DbType="BigInt")]
		public System.Nullable<long> AfterSaleId
		{
			get
			{
				return this._AfterSaleId;
			}
			set
			{
				if ((this._AfterSaleId != value))
				{
					this.OnAfterSaleIdChanging(value);
					this.SendPropertyChanging();
					this._AfterSaleId = value;
					this.SendPropertyChanged("AfterSaleId");
					this.OnAfterSaleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodPostageId", DbType="BigInt")]
		public System.Nullable<long> CodPostageId
		{
			get
			{
				return this._CodPostageId;
			}
			set
			{
				if ((this._CodPostageId != value))
				{
					this.OnCodPostageIdChanging(value);
					this.SendPropertyChanging();
					this._CodPostageId = value;
					this.SendPropertyChanged("CodPostageId");
					this.OnCodPostageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLightningConsignment", DbType="Bit")]
		public System.Nullable<bool> IsLightningConsignment
		{
			get
			{
				return this._IsLightningConsignment;
			}
			set
			{
				if ((this._IsLightningConsignment != value))
				{
					this.OnIsLightningConsignmentChanging(value);
					this.SendPropertyChanging();
					this._IsLightningConsignment = value;
					this.SendPropertyChanged("IsLightningConsignment");
					this.OnIsLightningConsignmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="BigInt")]
		public System.Nullable<long> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this.OnWeightChanging(value);
					this.SendPropertyChanging();
					this._Weight = value;
					this.SendPropertyChanged("Weight");
					this.OnWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsXinpin", DbType="Bit")]
		public System.Nullable<bool> IsXinpin
		{
			get
			{
				return this._IsXinpin;
			}
			set
			{
				if ((this._IsXinpin != value))
				{
					this.OnIsXinpinChanging(value);
					this.SendPropertyChanging();
					this._IsXinpin = value;
					this.SendPropertyChanged("IsXinpin");
					this.OnIsXinpinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubStock", DbType="BigInt")]
		public System.Nullable<long> SubStock
		{
			get
			{
				return this._SubStock;
			}
			set
			{
				if ((this._SubStock != value))
				{
					this.OnSubStockChanging(value);
					this.SendPropertyChanging();
					this._SubStock = value;
					this.SendPropertyChanged("SubStock");
					this.OnSubStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemSize", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> ItemSize
		{
			get
			{
				return this._ItemSize;
			}
			set
			{
				if ((this._ItemSize != value))
				{
					this.OnItemSizeChanging(value);
					this.SendPropertyChanging();
					this._ItemSize = value;
					this.SendPropertyChanged("ItemSize");
					this.OnItemSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemWeight", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> ItemWeight
		{
			get
			{
				return this._ItemWeight;
			}
			set
			{
				if ((this._ItemWeight != value))
				{
					this.OnItemWeightChanging(value);
					this.SendPropertyChanging();
					this._ItemWeight = value;
					this.SendPropertyChanged("ItemWeight");
					this.OnItemWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeProp", DbType="NVarChar(2000)")]
		public string ChangeProp
		{
			get
			{
				return this._ChangeProp;
			}
			set
			{
				if ((this._ChangeProp != value))
				{
					this.OnChangePropChanging(value);
					this.SendPropertyChanging();
					this._ChangeProp = value;
					this.SendPropertyChanged("ChangeProp");
					this.OnChangePropChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescModules", DbType="NVarChar(2000)")]
		public string DescModules
		{
			get
			{
				return this._DescModules;
			}
			set
			{
				if ((this._DescModules != value))
				{
					this.OnDescModulesChanging(value);
					this.SendPropertyChanging();
					this._DescModules = value;
					this.SendPropertyChanged("DescModules");
					this.OnDescModulesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalStockType", DbType="NVarChar(50)")]
		public string GlobalStockType
		{
			get
			{
				return this._GlobalStockType;
			}
			set
			{
				if ((this._GlobalStockType != value))
				{
					this.OnGlobalStockTypeChanging(value);
					this.SendPropertyChanging();
					this._GlobalStockType = value;
					this.SendPropertyChanged("GlobalStockType");
					this.OnGlobalStockTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GlobalStockCountry", DbType="NVarChar(200)")]
		public string GlobalStockCountry
		{
			get
			{
				return this._GlobalStockCountry;
			}
			set
			{
				if ((this._GlobalStockCountry != value))
				{
					this.OnGlobalStockCountryChanging(value);
					this.SendPropertyChanging();
					this._GlobalStockCountry = value;
					this.SendPropertyChanged("GlobalStockCountry");
					this.OnGlobalStockCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumIid", DbType="BigInt")]
		public System.Nullable<long> NumIid
		{
			get
			{
				return this._NumIid;
			}
			set
			{
				if ((this._NumIid != value))
				{
					this.OnNumIidChanging(value);
					this.SendPropertyChanging();
					this._NumIid = value;
					this.SendPropertyChanged("NumIid");
					this.OnNumIidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReplaceSku", DbType="Bit")]
		public System.Nullable<bool> IsReplaceSku
		{
			get
			{
				return this._IsReplaceSku;
			}
			set
			{
				if ((this._IsReplaceSku != value))
				{
					this.OnIsReplaceSkuChanging(value);
					this.SendPropertyChanging();
					this._IsReplaceSku = value;
					this.SendPropertyChanged("IsReplaceSku");
					this.OnIsReplaceSkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmptyFields", DbType="NVarChar(4000)")]
		public string EmptyFields
		{
			get
			{
				return this._EmptyFields;
			}
			set
			{
				if ((this._EmptyFields != value))
				{
					this.OnEmptyFieldsChanging(value);
					this.SendPropertyChanging();
					this._EmptyFields = value;
					this.SendPropertyChanged("EmptyFields");
					this.OnEmptyFieldsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSProductID", DbType="BigInt")]
		public System.Nullable<long> SSProductID
		{
			get
			{
				return this._SSProductID;
			}
			set
			{
				if ((this._SSProductID != value))
				{
					this.OnSSProductIDChanging(value);
					this.SendPropertyChanging();
					this._SSProductID = value;
					this.SendPropertyChanged("SSProductID");
					this.OnSSProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUploaded", DbType="Bit")]
		public System.Nullable<bool> IsUploaded
		{
			get
			{
				return this._IsUploaded;
			}
			set
			{
				if ((this._IsUploaded != value))
				{
					this.OnIsUploadedChanging(value);
					this.SendPropertyChanging();
					this._IsUploaded = value;
					this.SendPropertyChanged("IsUploaded");
					this.OnIsUploadedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PropValue")]
	public partial class TB_PropValue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Nullable<long> _Cid;
		
		private System.Nullable<bool> _IsParent;
		
		private System.Nullable<System.DateTime> _ModifiedTime;
		
		private string _ModifiedType;
		
		private string _Name;
		
		private string _NameAlias;
		
		private System.Nullable<long> _Pid;
		
		private string _PropName;
		
		private System.Nullable<long> _SortOrder;
		
		private string _Status;
		
		private System.Nullable<long> _Vid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCidChanging(System.Nullable<long> value);
    partial void OnCidChanged();
    partial void OnIsParentChanging(System.Nullable<bool> value);
    partial void OnIsParentChanged();
    partial void OnModifiedTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedTimeChanged();
    partial void OnModifiedTypeChanging(string value);
    partial void OnModifiedTypeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNameAliasChanging(string value);
    partial void OnNameAliasChanged();
    partial void OnPidChanging(System.Nullable<long> value);
    partial void OnPidChanged();
    partial void OnPropNameChanging(string value);
    partial void OnPropNameChanged();
    partial void OnSortOrderChanging(System.Nullable<long> value);
    partial void OnSortOrderChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnVidChanging(System.Nullable<long> value);
    partial void OnVidChanged();
    #endregion
		
		public TB_PropValue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", DbType="BigInt")]
		public System.Nullable<long> Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="Bit")]
		public System.Nullable<bool> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this.OnIsParentChanging(value);
					this.SendPropertyChanging();
					this._IsParent = value;
					this.SendPropertyChanged("IsParent");
					this.OnIsParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedTime
		{
			get
			{
				return this._ModifiedTime;
			}
			set
			{
				if ((this._ModifiedTime != value))
				{
					this.OnModifiedTimeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedTime = value;
					this.SendPropertyChanged("ModifiedTime");
					this.OnModifiedTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedType", DbType="NChar(50)")]
		public string ModifiedType
		{
			get
			{
				return this._ModifiedType;
			}
			set
			{
				if ((this._ModifiedType != value))
				{
					this.OnModifiedTypeChanging(value);
					this.SendPropertyChanging();
					this._ModifiedType = value;
					this.SendPropertyChanged("ModifiedType");
					this.OnModifiedTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameAlias", DbType="NVarChar(200)")]
		public string NameAlias
		{
			get
			{
				return this._NameAlias;
			}
			set
			{
				if ((this._NameAlias != value))
				{
					this.OnNameAliasChanging(value);
					this.SendPropertyChanging();
					this._NameAlias = value;
					this.SendPropertyChanged("NameAlias");
					this.OnNameAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pid", DbType="BigInt")]
		public System.Nullable<long> Pid
		{
			get
			{
				return this._Pid;
			}
			set
			{
				if ((this._Pid != value))
				{
					this.OnPidChanging(value);
					this.SendPropertyChanging();
					this._Pid = value;
					this.SendPropertyChanged("Pid");
					this.OnPidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropName", DbType="NVarChar(200)")]
		public string PropName
		{
			get
			{
				return this._PropName;
			}
			set
			{
				if ((this._PropName != value))
				{
					this.OnPropNameChanging(value);
					this.SendPropertyChanging();
					this._PropName = value;
					this.SendPropertyChanged("PropName");
					this.OnPropNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="BigInt")]
		public System.Nullable<long> SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vid", DbType="BigInt")]
		public System.Nullable<long> Vid
		{
			get
			{
				return this._Vid;
			}
			set
			{
				if ((this._Vid != value))
				{
					this.OnVidChanging(value);
					this.SendPropertyChanging();
					this._Vid = value;
					this.SendPropertyChanged("Vid");
					this.OnVidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
